// Code generated by ent, DO NOT EDIT.

package pricingplanmodel

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the pricingplanmodel type in the database.
	Label = "pricing_plan_model"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldPublicModel holds the string denoting the public_model field in the database.
	FieldPublicModel = "public_model"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldDirect holds the string denoting the direct field in the database.
	FieldDirect = "direct"
	// FieldAllowCompatibilityFallback holds the string denoting the allow_compatibility_fallback field in the database.
	FieldAllowCompatibilityFallback = "allow_compatibility_fallback"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldPricing holds the string denoting the pricing field in the database.
	FieldPricing = "pricing"
	// EdgePlan holds the string denoting the plan edge name in mutations.
	EdgePlan = "plan"
	// Table holds the table name of the pricingplanmodel in the database.
	Table = "pricing_plan_models"
	// PlanTable is the table that holds the plan relation/edge.
	PlanTable = "pricing_plan_models"
	// PlanInverseTable is the table name for the PricingPlan entity.
	// It exists in this package in order to avoid circular dependency with the "pricingplan" package.
	PlanInverseTable = "pricing_plans"
	// PlanColumn is the table column denoting the plan relation/edge.
	PlanColumn = "plan_id"
)

// Columns holds all SQL columns for pricingplanmodel fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldPlanID,
	FieldPublicModel,
	FieldProtocol,
	FieldUpstreamModel,
	FieldDirect,
	FieldAllowCompatibilityFallback,
	FieldPriority,
	FieldEnabled,
	FieldNotes,
	FieldPricing,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// PublicModelValidator is a validator for the "public_model" field. It is called by the builders before save.
	PublicModelValidator func(string) error
	// DefaultProtocol holds the default value on creation for the "protocol" field.
	DefaultProtocol string
	// ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	ProtocolValidator func(string) error
	// DefaultUpstreamModel holds the default value on creation for the "upstream_model" field.
	DefaultUpstreamModel string
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// DefaultDirect holds the default value on creation for the "direct" field.
	DefaultDirect bool
	// DefaultAllowCompatibilityFallback holds the default value on creation for the "allow_compatibility_fallback" field.
	DefaultAllowCompatibilityFallback bool
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
)

// OrderOption defines the ordering options for the PricingPlanModel queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByPublicModel orders the results by the public_model field.
func ByPublicModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicModel, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByDirect orders the results by the direct field.
func ByDirect(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirect, opts...).ToFunc()
}

// ByAllowCompatibilityFallback orders the results by the allow_compatibility_fallback field.
func ByAllowCompatibilityFallback(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowCompatibilityFallback, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByPlanField orders the results by plan field.
func ByPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlanStep(), sql.OrderByField(field, opts...))
	}
}
func newPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PlanTable, PlanColumn),
	)
}
