// Code generated by ent, DO NOT EDIT.

package pricingplanmodel

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldDeletedAt, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldPlanID, v))
}

// PublicModel applies equality check predicate on the "public_model" field. It's identical to PublicModelEQ.
func PublicModel(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldPublicModel, v))
}

// Protocol applies equality check predicate on the "protocol" field. It's identical to ProtocolEQ.
func Protocol(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldProtocol, v))
}

// UpstreamModel applies equality check predicate on the "upstream_model" field. It's identical to UpstreamModelEQ.
func UpstreamModel(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldUpstreamModel, v))
}

// Direct applies equality check predicate on the "direct" field. It's identical to DirectEQ.
func Direct(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldDirect, v))
}

// AllowCompatibilityFallback applies equality check predicate on the "allow_compatibility_fallback" field. It's identical to AllowCompatibilityFallbackEQ.
func AllowCompatibilityFallback(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldAllowCompatibilityFallback, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldPriority, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldEnabled, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldNotes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotNull(FieldDeletedAt))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...int64) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldPlanID, vs...))
}

// PublicModelEQ applies the EQ predicate on the "public_model" field.
func PublicModelEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldPublicModel, v))
}

// PublicModelNEQ applies the NEQ predicate on the "public_model" field.
func PublicModelNEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldPublicModel, v))
}

// PublicModelIn applies the In predicate on the "public_model" field.
func PublicModelIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldPublicModel, vs...))
}

// PublicModelNotIn applies the NotIn predicate on the "public_model" field.
func PublicModelNotIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldPublicModel, vs...))
}

// PublicModelGT applies the GT predicate on the "public_model" field.
func PublicModelGT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldPublicModel, v))
}

// PublicModelGTE applies the GTE predicate on the "public_model" field.
func PublicModelGTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldPublicModel, v))
}

// PublicModelLT applies the LT predicate on the "public_model" field.
func PublicModelLT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldPublicModel, v))
}

// PublicModelLTE applies the LTE predicate on the "public_model" field.
func PublicModelLTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldPublicModel, v))
}

// PublicModelContains applies the Contains predicate on the "public_model" field.
func PublicModelContains(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContains(FieldPublicModel, v))
}

// PublicModelHasPrefix applies the HasPrefix predicate on the "public_model" field.
func PublicModelHasPrefix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasPrefix(FieldPublicModel, v))
}

// PublicModelHasSuffix applies the HasSuffix predicate on the "public_model" field.
func PublicModelHasSuffix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasSuffix(FieldPublicModel, v))
}

// PublicModelEqualFold applies the EqualFold predicate on the "public_model" field.
func PublicModelEqualFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEqualFold(FieldPublicModel, v))
}

// PublicModelContainsFold applies the ContainsFold predicate on the "public_model" field.
func PublicModelContainsFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContainsFold(FieldPublicModel, v))
}

// ProtocolEQ applies the EQ predicate on the "protocol" field.
func ProtocolEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldProtocol, v))
}

// ProtocolNEQ applies the NEQ predicate on the "protocol" field.
func ProtocolNEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldProtocol, v))
}

// ProtocolIn applies the In predicate on the "protocol" field.
func ProtocolIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldProtocol, vs...))
}

// ProtocolNotIn applies the NotIn predicate on the "protocol" field.
func ProtocolNotIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldProtocol, vs...))
}

// ProtocolGT applies the GT predicate on the "protocol" field.
func ProtocolGT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldProtocol, v))
}

// ProtocolGTE applies the GTE predicate on the "protocol" field.
func ProtocolGTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldProtocol, v))
}

// ProtocolLT applies the LT predicate on the "protocol" field.
func ProtocolLT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldProtocol, v))
}

// ProtocolLTE applies the LTE predicate on the "protocol" field.
func ProtocolLTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldProtocol, v))
}

// ProtocolContains applies the Contains predicate on the "protocol" field.
func ProtocolContains(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContains(FieldProtocol, v))
}

// ProtocolHasPrefix applies the HasPrefix predicate on the "protocol" field.
func ProtocolHasPrefix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasPrefix(FieldProtocol, v))
}

// ProtocolHasSuffix applies the HasSuffix predicate on the "protocol" field.
func ProtocolHasSuffix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasSuffix(FieldProtocol, v))
}

// ProtocolEqualFold applies the EqualFold predicate on the "protocol" field.
func ProtocolEqualFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEqualFold(FieldProtocol, v))
}

// ProtocolContainsFold applies the ContainsFold predicate on the "protocol" field.
func ProtocolContainsFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContainsFold(FieldProtocol, v))
}

// UpstreamModelEQ applies the EQ predicate on the "upstream_model" field.
func UpstreamModelEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldUpstreamModel, v))
}

// UpstreamModelNEQ applies the NEQ predicate on the "upstream_model" field.
func UpstreamModelNEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldUpstreamModel, v))
}

// UpstreamModelIn applies the In predicate on the "upstream_model" field.
func UpstreamModelIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldUpstreamModel, vs...))
}

// UpstreamModelNotIn applies the NotIn predicate on the "upstream_model" field.
func UpstreamModelNotIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldUpstreamModel, vs...))
}

// UpstreamModelGT applies the GT predicate on the "upstream_model" field.
func UpstreamModelGT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldUpstreamModel, v))
}

// UpstreamModelGTE applies the GTE predicate on the "upstream_model" field.
func UpstreamModelGTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldUpstreamModel, v))
}

// UpstreamModelLT applies the LT predicate on the "upstream_model" field.
func UpstreamModelLT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldUpstreamModel, v))
}

// UpstreamModelLTE applies the LTE predicate on the "upstream_model" field.
func UpstreamModelLTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldUpstreamModel, v))
}

// UpstreamModelContains applies the Contains predicate on the "upstream_model" field.
func UpstreamModelContains(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContains(FieldUpstreamModel, v))
}

// UpstreamModelHasPrefix applies the HasPrefix predicate on the "upstream_model" field.
func UpstreamModelHasPrefix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasPrefix(FieldUpstreamModel, v))
}

// UpstreamModelHasSuffix applies the HasSuffix predicate on the "upstream_model" field.
func UpstreamModelHasSuffix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasSuffix(FieldUpstreamModel, v))
}

// UpstreamModelEqualFold applies the EqualFold predicate on the "upstream_model" field.
func UpstreamModelEqualFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEqualFold(FieldUpstreamModel, v))
}

// UpstreamModelContainsFold applies the ContainsFold predicate on the "upstream_model" field.
func UpstreamModelContainsFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContainsFold(FieldUpstreamModel, v))
}

// DirectEQ applies the EQ predicate on the "direct" field.
func DirectEQ(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldDirect, v))
}

// DirectNEQ applies the NEQ predicate on the "direct" field.
func DirectNEQ(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldDirect, v))
}

// AllowCompatibilityFallbackEQ applies the EQ predicate on the "allow_compatibility_fallback" field.
func AllowCompatibilityFallbackEQ(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldAllowCompatibilityFallback, v))
}

// AllowCompatibilityFallbackNEQ applies the NEQ predicate on the "allow_compatibility_fallback" field.
func AllowCompatibilityFallbackNEQ(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldAllowCompatibilityFallback, v))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldPriority, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldEnabled, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldContainsFold(FieldNotes, v))
}

// PricingIsNil applies the IsNil predicate on the "pricing" field.
func PricingIsNil() predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldIsNull(FieldPricing))
}

// PricingNotNil applies the NotNil predicate on the "pricing" field.
func PricingNotNil() predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.FieldNotNull(FieldPricing))
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.PricingPlanModel {
	return predicate.PricingPlanModel(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.PricingPlan) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PricingPlanModel) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PricingPlanModel) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PricingPlanModel) predicate.PricingPlanModel {
	return predicate.PricingPlanModel(sql.NotPredicates(p))
}
