// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanmodel"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// PricingPlanModelCreate is the builder for creating a PricingPlanModel entity.
type PricingPlanModelCreate struct {
	config
	mutation *PricingPlanModelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PricingPlanModelCreate) SetCreatedAt(v time.Time) *PricingPlanModelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableCreatedAt(v *time.Time) *PricingPlanModelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PricingPlanModelCreate) SetUpdatedAt(v time.Time) *PricingPlanModelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableUpdatedAt(v *time.Time) *PricingPlanModelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PricingPlanModelCreate) SetDeletedAt(v time.Time) *PricingPlanModelCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableDeletedAt(v *time.Time) *PricingPlanModelCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *PricingPlanModelCreate) SetPlanID(v int64) *PricingPlanModelCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetPublicModel sets the "public_model" field.
func (_c *PricingPlanModelCreate) SetPublicModel(v string) *PricingPlanModelCreate {
	_c.mutation.SetPublicModel(v)
	return _c
}

// SetProtocol sets the "protocol" field.
func (_c *PricingPlanModelCreate) SetProtocol(v string) *PricingPlanModelCreate {
	_c.mutation.SetProtocol(v)
	return _c
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableProtocol(v *string) *PricingPlanModelCreate {
	if v != nil {
		_c.SetProtocol(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *PricingPlanModelCreate) SetUpstreamModel(v string) *PricingPlanModelCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableUpstreamModel(v *string) *PricingPlanModelCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetDirect sets the "direct" field.
func (_c *PricingPlanModelCreate) SetDirect(v bool) *PricingPlanModelCreate {
	_c.mutation.SetDirect(v)
	return _c
}

// SetNillableDirect sets the "direct" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableDirect(v *bool) *PricingPlanModelCreate {
	if v != nil {
		_c.SetDirect(*v)
	}
	return _c
}

// SetAllowCompatibilityFallback sets the "allow_compatibility_fallback" field.
func (_c *PricingPlanModelCreate) SetAllowCompatibilityFallback(v bool) *PricingPlanModelCreate {
	_c.mutation.SetAllowCompatibilityFallback(v)
	return _c
}

// SetNillableAllowCompatibilityFallback sets the "allow_compatibility_fallback" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableAllowCompatibilityFallback(v *bool) *PricingPlanModelCreate {
	if v != nil {
		_c.SetAllowCompatibilityFallback(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *PricingPlanModelCreate) SetPriority(v int) *PricingPlanModelCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillablePriority(v *int) *PricingPlanModelCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PricingPlanModelCreate) SetEnabled(v bool) *PricingPlanModelCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableEnabled(v *bool) *PricingPlanModelCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *PricingPlanModelCreate) SetNotes(v string) *PricingPlanModelCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *PricingPlanModelCreate) SetNillableNotes(v *string) *PricingPlanModelCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetPricing sets the "pricing" field.
func (_c *PricingPlanModelCreate) SetPricing(v *domain.PlanModelPricing) *PricingPlanModelCreate {
	_c.mutation.SetPricing(v)
	return _c
}

// SetPlan sets the "plan" edge to the PricingPlan entity.
func (_c *PricingPlanModelCreate) SetPlan(v *PricingPlan) *PricingPlanModelCreate {
	return _c.SetPlanID(v.ID)
}

// Mutation returns the PricingPlanModelMutation object of the builder.
func (_c *PricingPlanModelCreate) Mutation() *PricingPlanModelMutation {
	return _c.mutation
}

// Save creates the PricingPlanModel in the database.
func (_c *PricingPlanModelCreate) Save(ctx context.Context) (*PricingPlanModel, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PricingPlanModelCreate) SaveX(ctx context.Context) *PricingPlanModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPlanModelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPlanModelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PricingPlanModelCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if pricingplanmodel.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanmodel.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanmodel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if pricingplanmodel.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanmodel.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanmodel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		v := pricingplanmodel.DefaultProtocol
		_c.mutation.SetProtocol(v)
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		v := pricingplanmodel.DefaultUpstreamModel
		_c.mutation.SetUpstreamModel(v)
	}
	if _, ok := _c.mutation.Direct(); !ok {
		v := pricingplanmodel.DefaultDirect
		_c.mutation.SetDirect(v)
	}
	if _, ok := _c.mutation.AllowCompatibilityFallback(); !ok {
		v := pricingplanmodel.DefaultAllowCompatibilityFallback
		_c.mutation.SetAllowCompatibilityFallback(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := pricingplanmodel.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := pricingplanmodel.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PricingPlanModelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PricingPlanModel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PricingPlanModel.updated_at"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "PricingPlanModel.plan_id"`)}
	}
	if _, ok := _c.mutation.PublicModel(); !ok {
		return &ValidationError{Name: "public_model", err: errors.New(`ent: missing required field "PricingPlanModel.public_model"`)}
	}
	if v, ok := _c.mutation.PublicModel(); ok {
		if err := pricingplanmodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.public_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Protocol(); !ok {
		return &ValidationError{Name: "protocol", err: errors.New(`ent: missing required field "PricingPlanModel.protocol"`)}
	}
	if v, ok := _c.mutation.Protocol(); ok {
		if err := pricingplanmodel.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.protocol": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpstreamModel(); !ok {
		return &ValidationError{Name: "upstream_model", err: errors.New(`ent: missing required field "PricingPlanModel.upstream_model"`)}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := pricingplanmodel.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.upstream_model": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Direct(); !ok {
		return &ValidationError{Name: "direct", err: errors.New(`ent: missing required field "PricingPlanModel.direct"`)}
	}
	if _, ok := _c.mutation.AllowCompatibilityFallback(); !ok {
		return &ValidationError{Name: "allow_compatibility_fallback", err: errors.New(`ent: missing required field "PricingPlanModel.allow_compatibility_fallback"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "PricingPlanModel.priority"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PricingPlanModel.enabled"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "PricingPlanModel.plan"`)}
	}
	return nil
}

func (_c *PricingPlanModelCreate) sqlSave(ctx context.Context) (*PricingPlanModel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PricingPlanModelCreate) createSpec() (*PricingPlanModel, *sqlgraph.CreateSpec) {
	var (
		_node = &PricingPlanModel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricingplanmodel.Table, sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pricingplanmodel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplanmodel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplanmodel.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.PublicModel(); ok {
		_spec.SetField(pricingplanmodel.FieldPublicModel, field.TypeString, value)
		_node.PublicModel = value
	}
	if value, ok := _c.mutation.Protocol(); ok {
		_spec.SetField(pricingplanmodel.FieldProtocol, field.TypeString, value)
		_node.Protocol = value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(pricingplanmodel.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = value
	}
	if value, ok := _c.mutation.Direct(); ok {
		_spec.SetField(pricingplanmodel.FieldDirect, field.TypeBool, value)
		_node.Direct = value
	}
	if value, ok := _c.mutation.AllowCompatibilityFallback(); ok {
		_spec.SetField(pricingplanmodel.FieldAllowCompatibilityFallback, field.TypeBool, value)
		_node.AllowCompatibilityFallback = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(pricingplanmodel.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(pricingplanmodel.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(pricingplanmodel.FieldNotes, field.TypeString, value)
		_node.Notes = &value
	}
	if value, ok := _c.mutation.Pricing(); ok {
		_spec.SetField(pricingplanmodel.FieldPricing, field.TypeJSON, value)
		_node.Pricing = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanmodel.PlanTable,
			Columns: []string{pricingplanmodel.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingPlanModel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingPlanModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingPlanModelCreate) OnConflict(opts ...sql.ConflictOption) *PricingPlanModelUpsertOne {
	_c.conflict = opts
	return &PricingPlanModelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingPlanModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingPlanModelCreate) OnConflictColumns(columns ...string) *PricingPlanModelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingPlanModelUpsertOne{
		create: _c,
	}
}

type (
	// PricingPlanModelUpsertOne is the builder for "upsert"-ing
	//  one PricingPlanModel node.
	PricingPlanModelUpsertOne struct {
		create *PricingPlanModelCreate
	}

	// PricingPlanModelUpsert is the "OnConflict" setter.
	PricingPlanModelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanModelUpsert) SetUpdatedAt(v time.Time) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateUpdatedAt() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanModelUpsert) SetDeletedAt(v time.Time) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateDeletedAt() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanModelUpsert) ClearDeletedAt() *PricingPlanModelUpsert {
	u.SetNull(pricingplanmodel.FieldDeletedAt)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *PricingPlanModelUpsert) SetPlanID(v int64) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdatePlanID() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldPlanID)
	return u
}

// SetPublicModel sets the "public_model" field.
func (u *PricingPlanModelUpsert) SetPublicModel(v string) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldPublicModel, v)
	return u
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdatePublicModel() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldPublicModel)
	return u
}

// SetProtocol sets the "protocol" field.
func (u *PricingPlanModelUpsert) SetProtocol(v string) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldProtocol, v)
	return u
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateProtocol() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldProtocol)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PricingPlanModelUpsert) SetUpstreamModel(v string) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateUpstreamModel() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldUpstreamModel)
	return u
}

// SetDirect sets the "direct" field.
func (u *PricingPlanModelUpsert) SetDirect(v bool) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldDirect, v)
	return u
}

// UpdateDirect sets the "direct" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateDirect() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldDirect)
	return u
}

// SetAllowCompatibilityFallback sets the "allow_compatibility_fallback" field.
func (u *PricingPlanModelUpsert) SetAllowCompatibilityFallback(v bool) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldAllowCompatibilityFallback, v)
	return u
}

// UpdateAllowCompatibilityFallback sets the "allow_compatibility_fallback" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateAllowCompatibilityFallback() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldAllowCompatibilityFallback)
	return u
}

// SetPriority sets the "priority" field.
func (u *PricingPlanModelUpsert) SetPriority(v int) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdatePriority() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *PricingPlanModelUpsert) AddPriority(v int) *PricingPlanModelUpsert {
	u.Add(pricingplanmodel.FieldPriority, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PricingPlanModelUpsert) SetEnabled(v bool) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateEnabled() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldEnabled)
	return u
}

// SetNotes sets the "notes" field.
func (u *PricingPlanModelUpsert) SetNotes(v string) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdateNotes() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *PricingPlanModelUpsert) ClearNotes() *PricingPlanModelUpsert {
	u.SetNull(pricingplanmodel.FieldNotes)
	return u
}

// SetPricing sets the "pricing" field.
func (u *PricingPlanModelUpsert) SetPricing(v *domain.PlanModelPricing) *PricingPlanModelUpsert {
	u.Set(pricingplanmodel.FieldPricing, v)
	return u
}

// UpdatePricing sets the "pricing" field to the value that was provided on create.
func (u *PricingPlanModelUpsert) UpdatePricing() *PricingPlanModelUpsert {
	u.SetExcluded(pricingplanmodel.FieldPricing)
	return u
}

// ClearPricing clears the value of the "pricing" field.
func (u *PricingPlanModelUpsert) ClearPricing() *PricingPlanModelUpsert {
	u.SetNull(pricingplanmodel.FieldPricing)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PricingPlanModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingPlanModelUpsertOne) UpdateNewValues() *PricingPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pricingplanmodel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingPlanModel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PricingPlanModelUpsertOne) Ignore() *PricingPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingPlanModelUpsertOne) DoNothing() *PricingPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingPlanModelCreate.OnConflict
// documentation for more info.
func (u *PricingPlanModelUpsertOne) Update(set func(*PricingPlanModelUpsert)) *PricingPlanModelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingPlanModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanModelUpsertOne) SetUpdatedAt(v time.Time) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateUpdatedAt() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanModelUpsertOne) SetDeletedAt(v time.Time) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateDeletedAt() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanModelUpsertOne) ClearDeletedAt() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PricingPlanModelUpsertOne) SetPlanID(v int64) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdatePlanID() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePlanID()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *PricingPlanModelUpsertOne) SetPublicModel(v string) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdatePublicModel() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePublicModel()
	})
}

// SetProtocol sets the "protocol" field.
func (u *PricingPlanModelUpsertOne) SetProtocol(v string) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateProtocol() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateProtocol()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PricingPlanModelUpsertOne) SetUpstreamModel(v string) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateUpstreamModel() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetDirect sets the "direct" field.
func (u *PricingPlanModelUpsertOne) SetDirect(v bool) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetDirect(v)
	})
}

// UpdateDirect sets the "direct" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateDirect() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateDirect()
	})
}

// SetAllowCompatibilityFallback sets the "allow_compatibility_fallback" field.
func (u *PricingPlanModelUpsertOne) SetAllowCompatibilityFallback(v bool) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetAllowCompatibilityFallback(v)
	})
}

// UpdateAllowCompatibilityFallback sets the "allow_compatibility_fallback" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateAllowCompatibilityFallback() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateAllowCompatibilityFallback()
	})
}

// SetPriority sets the "priority" field.
func (u *PricingPlanModelUpsertOne) SetPriority(v int) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *PricingPlanModelUpsertOne) AddPriority(v int) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdatePriority() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PricingPlanModelUpsertOne) SetEnabled(v bool) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateEnabled() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetNotes sets the "notes" field.
func (u *PricingPlanModelUpsertOne) SetNotes(v string) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdateNotes() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PricingPlanModelUpsertOne) ClearNotes() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.ClearNotes()
	})
}

// SetPricing sets the "pricing" field.
func (u *PricingPlanModelUpsertOne) SetPricing(v *domain.PlanModelPricing) *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPricing(v)
	})
}

// UpdatePricing sets the "pricing" field to the value that was provided on create.
func (u *PricingPlanModelUpsertOne) UpdatePricing() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePricing()
	})
}

// ClearPricing clears the value of the "pricing" field.
func (u *PricingPlanModelUpsertOne) ClearPricing() *PricingPlanModelUpsertOne {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.ClearPricing()
	})
}

// Exec executes the query.
func (u *PricingPlanModelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingPlanModelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingPlanModelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PricingPlanModelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PricingPlanModelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PricingPlanModelCreateBulk is the builder for creating many PricingPlanModel entities in bulk.
type PricingPlanModelCreateBulk struct {
	config
	err      error
	builders []*PricingPlanModelCreate
	conflict []sql.ConflictOption
}

// Save creates the PricingPlanModel entities in the database.
func (_c *PricingPlanModelCreateBulk) Save(ctx context.Context) ([]*PricingPlanModel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PricingPlanModel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PricingPlanModelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PricingPlanModelCreateBulk) SaveX(ctx context.Context) []*PricingPlanModel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPlanModelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPlanModelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingPlanModel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingPlanModelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingPlanModelCreateBulk) OnConflict(opts ...sql.ConflictOption) *PricingPlanModelUpsertBulk {
	_c.conflict = opts
	return &PricingPlanModelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingPlanModel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingPlanModelCreateBulk) OnConflictColumns(columns ...string) *PricingPlanModelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingPlanModelUpsertBulk{
		create: _c,
	}
}

// PricingPlanModelUpsertBulk is the builder for "upsert"-ing
// a bulk of PricingPlanModel nodes.
type PricingPlanModelUpsertBulk struct {
	create *PricingPlanModelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PricingPlanModel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingPlanModelUpsertBulk) UpdateNewValues() *PricingPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pricingplanmodel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingPlanModel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PricingPlanModelUpsertBulk) Ignore() *PricingPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingPlanModelUpsertBulk) DoNothing() *PricingPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingPlanModelCreateBulk.OnConflict
// documentation for more info.
func (u *PricingPlanModelUpsertBulk) Update(set func(*PricingPlanModelUpsert)) *PricingPlanModelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingPlanModelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanModelUpsertBulk) SetUpdatedAt(v time.Time) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateUpdatedAt() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanModelUpsertBulk) SetDeletedAt(v time.Time) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateDeletedAt() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanModelUpsertBulk) ClearDeletedAt() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PricingPlanModelUpsertBulk) SetPlanID(v int64) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdatePlanID() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePlanID()
	})
}

// SetPublicModel sets the "public_model" field.
func (u *PricingPlanModelUpsertBulk) SetPublicModel(v string) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPublicModel(v)
	})
}

// UpdatePublicModel sets the "public_model" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdatePublicModel() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePublicModel()
	})
}

// SetProtocol sets the "protocol" field.
func (u *PricingPlanModelUpsertBulk) SetProtocol(v string) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetProtocol(v)
	})
}

// UpdateProtocol sets the "protocol" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateProtocol() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateProtocol()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PricingPlanModelUpsertBulk) SetUpstreamModel(v string) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateUpstreamModel() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateUpstreamModel()
	})
}

// SetDirect sets the "direct" field.
func (u *PricingPlanModelUpsertBulk) SetDirect(v bool) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetDirect(v)
	})
}

// UpdateDirect sets the "direct" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateDirect() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateDirect()
	})
}

// SetAllowCompatibilityFallback sets the "allow_compatibility_fallback" field.
func (u *PricingPlanModelUpsertBulk) SetAllowCompatibilityFallback(v bool) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetAllowCompatibilityFallback(v)
	})
}

// UpdateAllowCompatibilityFallback sets the "allow_compatibility_fallback" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateAllowCompatibilityFallback() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateAllowCompatibilityFallback()
	})
}

// SetPriority sets the "priority" field.
func (u *PricingPlanModelUpsertBulk) SetPriority(v int) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *PricingPlanModelUpsertBulk) AddPriority(v int) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdatePriority() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PricingPlanModelUpsertBulk) SetEnabled(v bool) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateEnabled() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateEnabled()
	})
}

// SetNotes sets the "notes" field.
func (u *PricingPlanModelUpsertBulk) SetNotes(v string) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdateNotes() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *PricingPlanModelUpsertBulk) ClearNotes() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.ClearNotes()
	})
}

// SetPricing sets the "pricing" field.
func (u *PricingPlanModelUpsertBulk) SetPricing(v *domain.PlanModelPricing) *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.SetPricing(v)
	})
}

// UpdatePricing sets the "pricing" field to the value that was provided on create.
func (u *PricingPlanModelUpsertBulk) UpdatePricing() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.UpdatePricing()
	})
}

// ClearPricing clears the value of the "pricing" field.
func (u *PricingPlanModelUpsertBulk) ClearPricing() *PricingPlanModelUpsertBulk {
	return u.Update(func(s *PricingPlanModelUpsert) {
		s.ClearPricing()
	})
}

// Exec executes the query.
func (u *PricingPlanModelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PricingPlanModelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingPlanModelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingPlanModelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
