// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanmodel"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanroute"
)

// PricingPlanCreate is the builder for creating a PricingPlan entity.
type PricingPlanCreate struct {
	config
	mutation *PricingPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PricingPlanCreate) SetCreatedAt(v time.Time) *PricingPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableCreatedAt(v *time.Time) *PricingPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PricingPlanCreate) SetUpdatedAt(v time.Time) *PricingPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableUpdatedAt(v *time.Time) *PricingPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PricingPlanCreate) SetDeletedAt(v time.Time) *PricingPlanCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableDeletedAt(v *time.Time) *PricingPlanCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PricingPlanCreate) SetName(v string) *PricingPlanCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *PricingPlanCreate) SetTitle(v string) *PricingPlanCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableTitle(v *string) *PricingPlanCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *PricingPlanCreate) SetDescription(v string) *PricingPlanCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableDescription(v *string) *PricingPlanCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PricingPlanCreate) SetStatus(v string) *PricingPlanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableStatus(v *string) *PricingPlanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIsPublic sets the "is_public" field.
func (_c *PricingPlanCreate) SetIsPublic(v bool) *PricingPlanCreate {
	_c.mutation.SetIsPublic(v)
	return _c
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableIsPublic(v *bool) *PricingPlanCreate {
	if v != nil {
		_c.SetIsPublic(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *PricingPlanCreate) SetSortOrder(v int) *PricingPlanCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *PricingPlanCreate) SetNillableSortOrder(v *int) *PricingPlanCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// AddModelIDs adds the "models" edge to the PricingPlanModel entity by IDs.
func (_c *PricingPlanCreate) AddModelIDs(ids ...int64) *PricingPlanCreate {
	_c.mutation.AddModelIDs(ids...)
	return _c
}

// AddModels adds the "models" edges to the PricingPlanModel entity.
func (_c *PricingPlanCreate) AddModels(v ...*PricingPlanModel) *PricingPlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddModelIDs(ids...)
}

// AddRouteIDs adds the "routes" edge to the PricingPlanRoute entity by IDs.
func (_c *PricingPlanCreate) AddRouteIDs(ids ...int64) *PricingPlanCreate {
	_c.mutation.AddRouteIDs(ids...)
	return _c
}

// AddRoutes adds the "routes" edges to the PricingPlanRoute entity.
func (_c *PricingPlanCreate) AddRoutes(v ...*PricingPlanRoute) *PricingPlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRouteIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_c *PricingPlanCreate) AddAPIKeyIDs(ids ...int64) *PricingPlanCreate {
	_c.mutation.AddAPIKeyIDs(ids...)
	return _c
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_c *PricingPlanCreate) AddAPIKeys(v ...*APIKey) *PricingPlanCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAPIKeyIDs(ids...)
}

// Mutation returns the PricingPlanMutation object of the builder.
func (_c *PricingPlanCreate) Mutation() *PricingPlanMutation {
	return _c.mutation
}

// Save creates the PricingPlan in the database.
func (_c *PricingPlanCreate) Save(ctx context.Context) (*PricingPlan, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PricingPlanCreate) SaveX(ctx context.Context) *PricingPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PricingPlanCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if pricingplan.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplan.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if pricingplan.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplan.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := pricingplan.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := pricingplan.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		v := pricingplan.DefaultIsPublic
		_c.mutation.SetIsPublic(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := pricingplan.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PricingPlanCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PricingPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PricingPlan.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PricingPlan.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := pricingplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "PricingPlan.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := pricingplan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PricingPlan.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := pricingplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsPublic(); !ok {
		return &ValidationError{Name: "is_public", err: errors.New(`ent: missing required field "PricingPlan.is_public"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "PricingPlan.sort_order"`)}
	}
	return nil
}

func (_c *PricingPlanCreate) sqlSave(ctx context.Context) (*PricingPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PricingPlanCreate) createSpec() (*PricingPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &PricingPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricingplan.Table, sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pricingplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplan.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(pricingplan.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(pricingplan.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(pricingplan.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(pricingplan.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.IsPublic(); ok {
		_spec.SetField(pricingplan.FieldIsPublic, field.TypeBool, value)
		_node.IsPublic = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(pricingplan.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if nodes := _c.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.ModelsTable,
			Columns: []string{pricingplan.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.RoutesTable,
			Columns: []string{pricingplan.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricingplan.APIKeysTable,
			Columns: []string{pricingplan.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingPlan.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingPlanCreate) OnConflict(opts ...sql.ConflictOption) *PricingPlanUpsertOne {
	_c.conflict = opts
	return &PricingPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingPlanCreate) OnConflictColumns(columns ...string) *PricingPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingPlanUpsertOne{
		create: _c,
	}
}

type (
	// PricingPlanUpsertOne is the builder for "upsert"-ing
	//  one PricingPlan node.
	PricingPlanUpsertOne struct {
		create *PricingPlanCreate
	}

	// PricingPlanUpsert is the "OnConflict" setter.
	PricingPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanUpsert) SetUpdatedAt(v time.Time) *PricingPlanUpsert {
	u.Set(pricingplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateUpdatedAt() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanUpsert) SetDeletedAt(v time.Time) *PricingPlanUpsert {
	u.Set(pricingplan.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateDeletedAt() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanUpsert) ClearDeletedAt() *PricingPlanUpsert {
	u.SetNull(pricingplan.FieldDeletedAt)
	return u
}

// SetName sets the "name" field.
func (u *PricingPlanUpsert) SetName(v string) *PricingPlanUpsert {
	u.Set(pricingplan.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateName() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldName)
	return u
}

// SetTitle sets the "title" field.
func (u *PricingPlanUpsert) SetTitle(v string) *PricingPlanUpsert {
	u.Set(pricingplan.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateTitle() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldTitle)
	return u
}

// SetDescription sets the "description" field.
func (u *PricingPlanUpsert) SetDescription(v string) *PricingPlanUpsert {
	u.Set(pricingplan.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateDescription() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PricingPlanUpsert) ClearDescription() *PricingPlanUpsert {
	u.SetNull(pricingplan.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *PricingPlanUpsert) SetStatus(v string) *PricingPlanUpsert {
	u.Set(pricingplan.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateStatus() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldStatus)
	return u
}

// SetIsPublic sets the "is_public" field.
func (u *PricingPlanUpsert) SetIsPublic(v bool) *PricingPlanUpsert {
	u.Set(pricingplan.FieldIsPublic, v)
	return u
}

// UpdateIsPublic sets the "is_public" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateIsPublic() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldIsPublic)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *PricingPlanUpsert) SetSortOrder(v int) *PricingPlanUpsert {
	u.Set(pricingplan.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PricingPlanUpsert) UpdateSortOrder() *PricingPlanUpsert {
	u.SetExcluded(pricingplan.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PricingPlanUpsert) AddSortOrder(v int) *PricingPlanUpsert {
	u.Add(pricingplan.FieldSortOrder, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PricingPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingPlanUpsertOne) UpdateNewValues() *PricingPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pricingplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PricingPlanUpsertOne) Ignore() *PricingPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingPlanUpsertOne) DoNothing() *PricingPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingPlanCreate.OnConflict
// documentation for more info.
func (u *PricingPlanUpsertOne) Update(set func(*PricingPlanUpsert)) *PricingPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanUpsertOne) SetUpdatedAt(v time.Time) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateUpdatedAt() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanUpsertOne) SetDeletedAt(v time.Time) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateDeletedAt() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanUpsertOne) ClearDeletedAt() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *PricingPlanUpsertOne) SetName(v string) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateName() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateName()
	})
}

// SetTitle sets the "title" field.
func (u *PricingPlanUpsertOne) SetTitle(v string) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateTitle() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PricingPlanUpsertOne) SetDescription(v string) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateDescription() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PricingPlanUpsertOne) ClearDescription() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *PricingPlanUpsertOne) SetStatus(v string) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateStatus() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateStatus()
	})
}

// SetIsPublic sets the "is_public" field.
func (u *PricingPlanUpsertOne) SetIsPublic(v bool) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetIsPublic(v)
	})
}

// UpdateIsPublic sets the "is_public" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateIsPublic() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateIsPublic()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PricingPlanUpsertOne) SetSortOrder(v int) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PricingPlanUpsertOne) AddSortOrder(v int) *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PricingPlanUpsertOne) UpdateSortOrder() *PricingPlanUpsertOne {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *PricingPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PricingPlanUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PricingPlanUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PricingPlanCreateBulk is the builder for creating many PricingPlan entities in bulk.
type PricingPlanCreateBulk struct {
	config
	err      error
	builders []*PricingPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the PricingPlan entities in the database.
func (_c *PricingPlanCreateBulk) Save(ctx context.Context) ([]*PricingPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PricingPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PricingPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PricingPlanCreateBulk) SaveX(ctx context.Context) []*PricingPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingPlanUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *PricingPlanUpsertBulk {
	_c.conflict = opts
	return &PricingPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingPlanCreateBulk) OnConflictColumns(columns ...string) *PricingPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingPlanUpsertBulk{
		create: _c,
	}
}

// PricingPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of PricingPlan nodes.
type PricingPlanUpsertBulk struct {
	create *PricingPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PricingPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingPlanUpsertBulk) UpdateNewValues() *PricingPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pricingplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PricingPlanUpsertBulk) Ignore() *PricingPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingPlanUpsertBulk) DoNothing() *PricingPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingPlanCreateBulk.OnConflict
// documentation for more info.
func (u *PricingPlanUpsertBulk) Update(set func(*PricingPlanUpsert)) *PricingPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanUpsertBulk) SetUpdatedAt(v time.Time) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateUpdatedAt() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanUpsertBulk) SetDeletedAt(v time.Time) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateDeletedAt() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanUpsertBulk) ClearDeletedAt() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.ClearDeletedAt()
	})
}

// SetName sets the "name" field.
func (u *PricingPlanUpsertBulk) SetName(v string) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateName() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateName()
	})
}

// SetTitle sets the "title" field.
func (u *PricingPlanUpsertBulk) SetTitle(v string) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateTitle() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateTitle()
	})
}

// SetDescription sets the "description" field.
func (u *PricingPlanUpsertBulk) SetDescription(v string) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateDescription() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PricingPlanUpsertBulk) ClearDescription() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *PricingPlanUpsertBulk) SetStatus(v string) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateStatus() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateStatus()
	})
}

// SetIsPublic sets the "is_public" field.
func (u *PricingPlanUpsertBulk) SetIsPublic(v bool) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetIsPublic(v)
	})
}

// UpdateIsPublic sets the "is_public" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateIsPublic() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateIsPublic()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *PricingPlanUpsertBulk) SetSortOrder(v int) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *PricingPlanUpsertBulk) AddSortOrder(v int) *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *PricingPlanUpsertBulk) UpdateSortOrder() *PricingPlanUpsertBulk {
	return u.Update(func(s *PricingPlanUpsert) {
		s.UpdateSortOrder()
	})
}

// Exec executes the query.
func (u *PricingPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PricingPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
