// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
)

// PricingPlan is the model entity for the PricingPlan schema.
type PricingPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Stable plan key, unique among non-deleted rows.
	Name string `json:"name,omitempty"`
	// Public-facing display name.
	Title string `json:"title,omitempty"`
	// Public-facing plan description.
	Description *string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Exposed as a purchasable product in public listings.
	IsPublic bool `json:"is_public,omitempty"`
	// Ascending display order for product listings.
	SortOrder int `json:"sort_order,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PricingPlanQuery when eager-loading is set.
	Edges        PricingPlanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PricingPlanEdges holds the relations/edges for other nodes in the graph.
type PricingPlanEdges struct {
	// Models holds the value of the models edge.
	Models []*PricingPlanModel `json:"models,omitempty"`
	// Routes holds the value of the routes edge.
	Routes []*PricingPlanRoute `json:"routes,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ModelsOrErr returns the Models value or an error if the edge
// was not loaded in eager-loading.
func (e PricingPlanEdges) ModelsOrErr() ([]*PricingPlanModel, error) {
	if e.loadedTypes[0] {
		return e.Models, nil
	}
	return nil, &NotLoadedError{edge: "models"}
}

// RoutesOrErr returns the Routes value or an error if the edge
// was not loaded in eager-loading.
func (e PricingPlanEdges) RoutesOrErr() ([]*PricingPlanRoute, error) {
	if e.loadedTypes[1] {
		return e.Routes, nil
	}
	return nil, &NotLoadedError{edge: "routes"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e PricingPlanEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[2] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PricingPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricingplan.FieldIsPublic:
			values[i] = new(sql.NullBool)
		case pricingplan.FieldID, pricingplan.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case pricingplan.FieldName, pricingplan.FieldTitle, pricingplan.FieldDescription, pricingplan.FieldStatus:
			values[i] = new(sql.NullString)
		case pricingplan.FieldCreatedAt, pricingplan.FieldUpdatedAt, pricingplan.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PricingPlan fields.
func (_m *PricingPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricingplan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case pricingplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pricingplan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case pricingplan.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case pricingplan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case pricingplan.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case pricingplan.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case pricingplan.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case pricingplan.FieldIsPublic:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_public", values[i])
			} else if value.Valid {
				_m.IsPublic = value.Bool
			}
		case pricingplan.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PricingPlan.
// This includes values selected through modifiers, order, etc.
func (_m *PricingPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModels queries the "models" edge of the PricingPlan entity.
func (_m *PricingPlan) QueryModels() *PricingPlanModelQuery {
	return NewPricingPlanClient(_m.config).QueryModels(_m)
}

// QueryRoutes queries the "routes" edge of the PricingPlan entity.
func (_m *PricingPlan) QueryRoutes() *PricingPlanRouteQuery {
	return NewPricingPlanClient(_m.config).QueryRoutes(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the PricingPlan entity.
func (_m *PricingPlan) QueryAPIKeys() *APIKeyQuery {
	return NewPricingPlanClient(_m.config).QueryAPIKeys(_m)
}

// Update returns a builder for updating this PricingPlan.
// Note that you need to call PricingPlan.Unwrap() before calling this method if this PricingPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PricingPlan) Update() *PricingPlanUpdateOne {
	return NewPricingPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PricingPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PricingPlan) Unwrap() *PricingPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PricingPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PricingPlan) String() string {
	var builder strings.Builder
	builder.WriteString("PricingPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("is_public=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsPublic))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteByte(')')
	return builder.String()
}

// PricingPlans is a parsable slice of PricingPlan.
type PricingPlans []*PricingPlan
