// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanroute"
)

// PricingPlanRouteCreate is the builder for creating a PricingPlanRoute entity.
type PricingPlanRouteCreate struct {
	config
	mutation *PricingPlanRouteMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PricingPlanRouteCreate) SetCreatedAt(v time.Time) *PricingPlanRouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PricingPlanRouteCreate) SetNillableCreatedAt(v *time.Time) *PricingPlanRouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PricingPlanRouteCreate) SetUpdatedAt(v time.Time) *PricingPlanRouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PricingPlanRouteCreate) SetNillableUpdatedAt(v *time.Time) *PricingPlanRouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *PricingPlanRouteCreate) SetDeletedAt(v time.Time) *PricingPlanRouteCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *PricingPlanRouteCreate) SetNillableDeletedAt(v *time.Time) *PricingPlanRouteCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetPlanID sets the "plan_id" field.
func (_c *PricingPlanRouteCreate) SetPlanID(v int64) *PricingPlanRouteCreate {
	_c.mutation.SetPlanID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PricingPlanRouteCreate) SetGroupID(v int64) *PricingPlanRouteCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *PricingPlanRouteCreate) SetPriority(v int) *PricingPlanRouteCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *PricingPlanRouteCreate) SetNillablePriority(v *int) *PricingPlanRouteCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PricingPlanRouteCreate) SetEnabled(v bool) *PricingPlanRouteCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PricingPlanRouteCreate) SetNillableEnabled(v *bool) *PricingPlanRouteCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetPlan sets the "plan" edge to the PricingPlan entity.
func (_c *PricingPlanRouteCreate) SetPlan(v *PricingPlan) *PricingPlanRouteCreate {
	return _c.SetPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *PricingPlanRouteCreate) SetGroup(v *Group) *PricingPlanRouteCreate {
	return _c.SetGroupID(v.ID)
}

// Mutation returns the PricingPlanRouteMutation object of the builder.
func (_c *PricingPlanRouteCreate) Mutation() *PricingPlanRouteMutation {
	return _c.mutation
}

// Save creates the PricingPlanRoute in the database.
func (_c *PricingPlanRouteCreate) Save(ctx context.Context) (*PricingPlanRoute, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PricingPlanRouteCreate) SaveX(ctx context.Context) *PricingPlanRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPlanRouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPlanRouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PricingPlanRouteCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if pricingplanroute.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanroute.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanroute.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if pricingplanroute.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanroute.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanroute.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := pricingplanroute.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := pricingplanroute.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *PricingPlanRouteCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PricingPlanRoute.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PricingPlanRoute.updated_at"`)}
	}
	if _, ok := _c.mutation.PlanID(); !ok {
		return &ValidationError{Name: "plan_id", err: errors.New(`ent: missing required field "PricingPlanRoute.plan_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "PricingPlanRoute.group_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "PricingPlanRoute.priority"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PricingPlanRoute.enabled"`)}
	}
	if len(_c.mutation.PlanIDs()) == 0 {
		return &ValidationError{Name: "plan", err: errors.New(`ent: missing required edge "PricingPlanRoute.plan"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "PricingPlanRoute.group"`)}
	}
	return nil
}

func (_c *PricingPlanRouteCreate) sqlSave(ctx context.Context) (*PricingPlanRoute, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PricingPlanRouteCreate) createSpec() (*PricingPlanRoute, *sqlgraph.CreateSpec) {
	var (
		_node = &PricingPlanRoute{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pricingplanroute.Table, sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(pricingplanroute.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplanroute.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplanroute.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(pricingplanroute.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(pricingplanroute.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if nodes := _c.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.PlanTable,
			Columns: []string{pricingplanroute.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.GroupTable,
			Columns: []string{pricingplanroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingPlanRoute.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingPlanRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingPlanRouteCreate) OnConflict(opts ...sql.ConflictOption) *PricingPlanRouteUpsertOne {
	_c.conflict = opts
	return &PricingPlanRouteUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingPlanRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingPlanRouteCreate) OnConflictColumns(columns ...string) *PricingPlanRouteUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingPlanRouteUpsertOne{
		create: _c,
	}
}

type (
	// PricingPlanRouteUpsertOne is the builder for "upsert"-ing
	//  one PricingPlanRoute node.
	PricingPlanRouteUpsertOne struct {
		create *PricingPlanRouteCreate
	}

	// PricingPlanRouteUpsert is the "OnConflict" setter.
	PricingPlanRouteUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanRouteUpsert) SetUpdatedAt(v time.Time) *PricingPlanRouteUpsert {
	u.Set(pricingplanroute.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanRouteUpsert) UpdateUpdatedAt() *PricingPlanRouteUpsert {
	u.SetExcluded(pricingplanroute.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanRouteUpsert) SetDeletedAt(v time.Time) *PricingPlanRouteUpsert {
	u.Set(pricingplanroute.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanRouteUpsert) UpdateDeletedAt() *PricingPlanRouteUpsert {
	u.SetExcluded(pricingplanroute.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanRouteUpsert) ClearDeletedAt() *PricingPlanRouteUpsert {
	u.SetNull(pricingplanroute.FieldDeletedAt)
	return u
}

// SetPlanID sets the "plan_id" field.
func (u *PricingPlanRouteUpsert) SetPlanID(v int64) *PricingPlanRouteUpsert {
	u.Set(pricingplanroute.FieldPlanID, v)
	return u
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PricingPlanRouteUpsert) UpdatePlanID() *PricingPlanRouteUpsert {
	u.SetExcluded(pricingplanroute.FieldPlanID)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *PricingPlanRouteUpsert) SetGroupID(v int64) *PricingPlanRouteUpsert {
	u.Set(pricingplanroute.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PricingPlanRouteUpsert) UpdateGroupID() *PricingPlanRouteUpsert {
	u.SetExcluded(pricingplanroute.FieldGroupID)
	return u
}

// SetPriority sets the "priority" field.
func (u *PricingPlanRouteUpsert) SetPriority(v int) *PricingPlanRouteUpsert {
	u.Set(pricingplanroute.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingPlanRouteUpsert) UpdatePriority() *PricingPlanRouteUpsert {
	u.SetExcluded(pricingplanroute.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *PricingPlanRouteUpsert) AddPriority(v int) *PricingPlanRouteUpsert {
	u.Add(pricingplanroute.FieldPriority, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PricingPlanRouteUpsert) SetEnabled(v bool) *PricingPlanRouteUpsert {
	u.Set(pricingplanroute.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingPlanRouteUpsert) UpdateEnabled() *PricingPlanRouteUpsert {
	u.SetExcluded(pricingplanroute.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PricingPlanRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingPlanRouteUpsertOne) UpdateNewValues() *PricingPlanRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(pricingplanroute.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingPlanRoute.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PricingPlanRouteUpsertOne) Ignore() *PricingPlanRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingPlanRouteUpsertOne) DoNothing() *PricingPlanRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingPlanRouteCreate.OnConflict
// documentation for more info.
func (u *PricingPlanRouteUpsertOne) Update(set func(*PricingPlanRouteUpsert)) *PricingPlanRouteUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingPlanRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanRouteUpsertOne) SetUpdatedAt(v time.Time) *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertOne) UpdateUpdatedAt() *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanRouteUpsertOne) SetDeletedAt(v time.Time) *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertOne) UpdateDeletedAt() *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanRouteUpsertOne) ClearDeletedAt() *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PricingPlanRouteUpsertOne) SetPlanID(v int64) *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertOne) UpdatePlanID() *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdatePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PricingPlanRouteUpsertOne) SetGroupID(v int64) *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertOne) UpdateGroupID() *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *PricingPlanRouteUpsertOne) SetPriority(v int) *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *PricingPlanRouteUpsertOne) AddPriority(v int) *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertOne) UpdatePriority() *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PricingPlanRouteUpsertOne) SetEnabled(v bool) *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertOne) UpdateEnabled() *PricingPlanRouteUpsertOne {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *PricingPlanRouteUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingPlanRouteCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingPlanRouteUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PricingPlanRouteUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PricingPlanRouteUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PricingPlanRouteCreateBulk is the builder for creating many PricingPlanRoute entities in bulk.
type PricingPlanRouteCreateBulk struct {
	config
	err      error
	builders []*PricingPlanRouteCreate
	conflict []sql.ConflictOption
}

// Save creates the PricingPlanRoute entities in the database.
func (_c *PricingPlanRouteCreateBulk) Save(ctx context.Context) ([]*PricingPlanRoute, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PricingPlanRoute, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PricingPlanRouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PricingPlanRouteCreateBulk) SaveX(ctx context.Context) []*PricingPlanRoute {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PricingPlanRouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PricingPlanRouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PricingPlanRoute.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PricingPlanRouteUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PricingPlanRouteCreateBulk) OnConflict(opts ...sql.ConflictOption) *PricingPlanRouteUpsertBulk {
	_c.conflict = opts
	return &PricingPlanRouteUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PricingPlanRoute.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PricingPlanRouteCreateBulk) OnConflictColumns(columns ...string) *PricingPlanRouteUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PricingPlanRouteUpsertBulk{
		create: _c,
	}
}

// PricingPlanRouteUpsertBulk is the builder for "upsert"-ing
// a bulk of PricingPlanRoute nodes.
type PricingPlanRouteUpsertBulk struct {
	create *PricingPlanRouteCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PricingPlanRoute.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PricingPlanRouteUpsertBulk) UpdateNewValues() *PricingPlanRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(pricingplanroute.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PricingPlanRoute.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PricingPlanRouteUpsertBulk) Ignore() *PricingPlanRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PricingPlanRouteUpsertBulk) DoNothing() *PricingPlanRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PricingPlanRouteCreateBulk.OnConflict
// documentation for more info.
func (u *PricingPlanRouteUpsertBulk) Update(set func(*PricingPlanRouteUpsert)) *PricingPlanRouteUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PricingPlanRouteUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PricingPlanRouteUpsertBulk) SetUpdatedAt(v time.Time) *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertBulk) UpdateUpdatedAt() *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PricingPlanRouteUpsertBulk) SetDeletedAt(v time.Time) *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertBulk) UpdateDeletedAt() *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PricingPlanRouteUpsertBulk) ClearDeletedAt() *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.ClearDeletedAt()
	})
}

// SetPlanID sets the "plan_id" field.
func (u *PricingPlanRouteUpsertBulk) SetPlanID(v int64) *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetPlanID(v)
	})
}

// UpdatePlanID sets the "plan_id" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertBulk) UpdatePlanID() *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdatePlanID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PricingPlanRouteUpsertBulk) SetGroupID(v int64) *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertBulk) UpdateGroupID() *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *PricingPlanRouteUpsertBulk) SetPriority(v int) *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *PricingPlanRouteUpsertBulk) AddPriority(v int) *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertBulk) UpdatePriority() *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdatePriority()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PricingPlanRouteUpsertBulk) SetEnabled(v bool) *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PricingPlanRouteUpsertBulk) UpdateEnabled() *PricingPlanRouteUpsertBulk {
	return u.Update(func(s *PricingPlanRouteUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *PricingPlanRouteUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PricingPlanRouteCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PricingPlanRouteCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PricingPlanRouteUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
