// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanmodel"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// PricingPlanModel is the model entity for the PricingPlanModel schema.
type PricingPlanModel struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// PlanID holds the value of the "plan_id" field.
	PlanID int64 `json:"plan_id,omitempty"`
	// Client-facing model identifier.
	PublicModel string `json:"public_model,omitempty"`
	// Upstream API protocol served for this model.
	Protocol string `json:"protocol,omitempty"`
	// Provider model identifier; empty means public_model.
	UpstreamModel string `json:"upstream_model,omitempty"`
	// Serve the upstream directly through this protocol.
	Direct bool `json:"direct,omitempty"`
	// Fall back to a compatibility layer when direct serving fails.
	AllowCompatibilityFallback bool `json:"allow_compatibility_fallback,omitempty"`
	// Sort hint; lower values win.
	Priority int `json:"priority,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes *string `json:"notes,omitempty"`
	// Model pricing document (billing mode + price fields/intervals).
	Pricing *domain.PlanModelPricing `json:"pricing,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PricingPlanModelQuery when eager-loading is set.
	Edges        PricingPlanModelEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PricingPlanModelEdges holds the relations/edges for other nodes in the graph.
type PricingPlanModelEdges struct {
	// Plan holds the value of the plan edge.
	Plan *PricingPlan `json:"plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PlanOrErr returns the Plan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PricingPlanModelEdges) PlanOrErr() (*PricingPlan, error) {
	if e.Plan != nil {
		return e.Plan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: pricingplan.Label}
	}
	return nil, &NotLoadedError{edge: "plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PricingPlanModel) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pricingplanmodel.FieldPricing:
			values[i] = new([]byte)
		case pricingplanmodel.FieldDirect, pricingplanmodel.FieldAllowCompatibilityFallback, pricingplanmodel.FieldEnabled:
			values[i] = new(sql.NullBool)
		case pricingplanmodel.FieldID, pricingplanmodel.FieldPlanID, pricingplanmodel.FieldPriority:
			values[i] = new(sql.NullInt64)
		case pricingplanmodel.FieldPublicModel, pricingplanmodel.FieldProtocol, pricingplanmodel.FieldUpstreamModel, pricingplanmodel.FieldNotes:
			values[i] = new(sql.NullString)
		case pricingplanmodel.FieldCreatedAt, pricingplanmodel.FieldUpdatedAt, pricingplanmodel.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PricingPlanModel fields.
func (_m *PricingPlanModel) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pricingplanmodel.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case pricingplanmodel.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pricingplanmodel.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case pricingplanmodel.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case pricingplanmodel.FieldPlanID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field plan_id", values[i])
			} else if value.Valid {
				_m.PlanID = value.Int64
			}
		case pricingplanmodel.FieldPublicModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_model", values[i])
			} else if value.Valid {
				_m.PublicModel = value.String
			}
		case pricingplanmodel.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case pricingplanmodel.FieldUpstreamModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field upstream_model", values[i])
			} else if value.Valid {
				_m.UpstreamModel = value.String
			}
		case pricingplanmodel.FieldDirect:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field direct", values[i])
			} else if value.Valid {
				_m.Direct = value.Bool
			}
		case pricingplanmodel.FieldAllowCompatibilityFallback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_compatibility_fallback", values[i])
			} else if value.Valid {
				_m.AllowCompatibilityFallback = value.Bool
			}
		case pricingplanmodel.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		case pricingplanmodel.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case pricingplanmodel.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = new(string)
				*_m.Notes = value.String
			}
		case pricingplanmodel.FieldPricing:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field pricing", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Pricing); err != nil {
					return fmt.Errorf("unmarshal field pricing: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PricingPlanModel.
// This includes values selected through modifiers, order, etc.
func (_m *PricingPlanModel) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlan queries the "plan" edge of the PricingPlanModel entity.
func (_m *PricingPlanModel) QueryPlan() *PricingPlanQuery {
	return NewPricingPlanModelClient(_m.config).QueryPlan(_m)
}

// Update returns a builder for updating this PricingPlanModel.
// Note that you need to call PricingPlanModel.Unwrap() before calling this method if this PricingPlanModel
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PricingPlanModel) Update() *PricingPlanModelUpdateOne {
	return NewPricingPlanModelClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PricingPlanModel entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PricingPlanModel) Unwrap() *PricingPlanModel {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PricingPlanModel is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PricingPlanModel) String() string {
	var builder strings.Builder
	builder.WriteString("PricingPlanModel(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.PlanID))
	builder.WriteString(", ")
	builder.WriteString("public_model=")
	builder.WriteString(_m.PublicModel)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("upstream_model=")
	builder.WriteString(_m.UpstreamModel)
	builder.WriteString(", ")
	builder.WriteString("direct=")
	builder.WriteString(fmt.Sprintf("%v", _m.Direct))
	builder.WriteString(", ")
	builder.WriteString("allow_compatibility_fallback=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowCompatibilityFallback))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	if v := _m.Notes; v != nil {
		builder.WriteString("notes=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("pricing=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pricing))
	builder.WriteByte(')')
	return builder.String()
}

// PricingPlanModels is a parsable slice of PricingPlanModel.
type PricingPlanModels []*PricingPlanModel
