// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanroute"
)

// PricingPlanRouteUpdate is the builder for updating PricingPlanRoute entities.
type PricingPlanRouteUpdate struct {
	config
	hooks    []Hook
	mutation *PricingPlanRouteMutation
}

// Where appends a list predicates to the PricingPlanRouteUpdate builder.
func (_u *PricingPlanRouteUpdate) Where(ps ...predicate.PricingPlanRoute) *PricingPlanRouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingPlanRouteUpdate) SetUpdatedAt(v time.Time) *PricingPlanRouteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PricingPlanRouteUpdate) SetDeletedAt(v time.Time) *PricingPlanRouteUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PricingPlanRouteUpdate) SetNillableDeletedAt(v *time.Time) *PricingPlanRouteUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PricingPlanRouteUpdate) ClearDeletedAt() *PricingPlanRouteUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PricingPlanRouteUpdate) SetPlanID(v int64) *PricingPlanRouteUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PricingPlanRouteUpdate) SetNillablePlanID(v *int64) *PricingPlanRouteUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PricingPlanRouteUpdate) SetGroupID(v int64) *PricingPlanRouteUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PricingPlanRouteUpdate) SetNillableGroupID(v *int64) *PricingPlanRouteUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PricingPlanRouteUpdate) SetPriority(v int) *PricingPlanRouteUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PricingPlanRouteUpdate) SetNillablePriority(v *int) *PricingPlanRouteUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PricingPlanRouteUpdate) AddPriority(v int) *PricingPlanRouteUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PricingPlanRouteUpdate) SetEnabled(v bool) *PricingPlanRouteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PricingPlanRouteUpdate) SetNillableEnabled(v *bool) *PricingPlanRouteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPlan sets the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanRouteUpdate) SetPlan(v *PricingPlan) *PricingPlanRouteUpdate {
	return _u.SetPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PricingPlanRouteUpdate) SetGroup(v *Group) *PricingPlanRouteUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the PricingPlanRouteMutation object of the builder.
func (_u *PricingPlanRouteUpdate) Mutation() *PricingPlanRouteMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanRouteUpdate) ClearPlan() *PricingPlanRouteUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PricingPlanRouteUpdate) ClearGroup() *PricingPlanRouteUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PricingPlanRouteUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPlanRouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PricingPlanRouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPlanRouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingPlanRouteUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if pricingplanroute.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanroute.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPlanRouteUpdate) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PricingPlanRoute.plan"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PricingPlanRoute.group"`)
	}
	return nil
}

func (_u *PricingPlanRouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingplanroute.Table, pricingplanroute.Columns, sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplanroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplanroute.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(pricingplanroute.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pricingplanroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(pricingplanroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pricingplanroute.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.PlanTable,
			Columns: []string{pricingplanroute.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.PlanTable,
			Columns: []string{pricingplanroute.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.GroupTable,
			Columns: []string{pricingplanroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.GroupTable,
			Columns: []string{pricingplanroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingplanroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PricingPlanRouteUpdateOne is the builder for updating a single PricingPlanRoute entity.
type PricingPlanRouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingPlanRouteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingPlanRouteUpdateOne) SetUpdatedAt(v time.Time) *PricingPlanRouteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PricingPlanRouteUpdateOne) SetDeletedAt(v time.Time) *PricingPlanRouteUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PricingPlanRouteUpdateOne) SetNillableDeletedAt(v *time.Time) *PricingPlanRouteUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PricingPlanRouteUpdateOne) ClearDeletedAt() *PricingPlanRouteUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PricingPlanRouteUpdateOne) SetPlanID(v int64) *PricingPlanRouteUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PricingPlanRouteUpdateOne) SetNillablePlanID(v *int64) *PricingPlanRouteUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PricingPlanRouteUpdateOne) SetGroupID(v int64) *PricingPlanRouteUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PricingPlanRouteUpdateOne) SetNillableGroupID(v *int64) *PricingPlanRouteUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PricingPlanRouteUpdateOne) SetPriority(v int) *PricingPlanRouteUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PricingPlanRouteUpdateOne) SetNillablePriority(v *int) *PricingPlanRouteUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PricingPlanRouteUpdateOne) AddPriority(v int) *PricingPlanRouteUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PricingPlanRouteUpdateOne) SetEnabled(v bool) *PricingPlanRouteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PricingPlanRouteUpdateOne) SetNillableEnabled(v *bool) *PricingPlanRouteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetPlan sets the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanRouteUpdateOne) SetPlan(v *PricingPlan) *PricingPlanRouteUpdateOne {
	return _u.SetPlanID(v.ID)
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PricingPlanRouteUpdateOne) SetGroup(v *Group) *PricingPlanRouteUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the PricingPlanRouteMutation object of the builder.
func (_u *PricingPlanRouteUpdateOne) Mutation() *PricingPlanRouteMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanRouteUpdateOne) ClearPlan() *PricingPlanRouteUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PricingPlanRouteUpdateOne) ClearGroup() *PricingPlanRouteUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the PricingPlanRouteUpdate builder.
func (_u *PricingPlanRouteUpdateOne) Where(ps ...predicate.PricingPlanRoute) *PricingPlanRouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PricingPlanRouteUpdateOne) Select(field string, fields ...string) *PricingPlanRouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PricingPlanRoute entity.
func (_u *PricingPlanRouteUpdateOne) Save(ctx context.Context) (*PricingPlanRoute, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPlanRouteUpdateOne) SaveX(ctx context.Context) *PricingPlanRoute {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PricingPlanRouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPlanRouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingPlanRouteUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if pricingplanroute.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanroute.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanroute.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPlanRouteUpdateOne) check() error {
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PricingPlanRoute.plan"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PricingPlanRoute.group"`)
	}
	return nil
}

func (_u *PricingPlanRouteUpdateOne) sqlSave(ctx context.Context) (_node *PricingPlanRoute, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingplanroute.Table, pricingplanroute.Columns, sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PricingPlanRoute.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingplanroute.FieldID)
		for _, f := range fields {
			if !pricingplanroute.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricingplanroute.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplanroute.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplanroute.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(pricingplanroute.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pricingplanroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(pricingplanroute.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pricingplanroute.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.PlanTable,
			Columns: []string{pricingplanroute.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.PlanTable,
			Columns: []string{pricingplanroute.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.GroupTable,
			Columns: []string{pricingplanroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanroute.GroupTable,
			Columns: []string{pricingplanroute.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PricingPlanRoute{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingplanroute.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
