// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanmodel"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanroute"
)

// PricingPlanQuery is the builder for querying PricingPlan entities.
type PricingPlanQuery struct {
	config
	ctx         *QueryContext
	order       []pricingplan.OrderOption
	inters      []Interceptor
	predicates  []predicate.PricingPlan
	withModels  *PricingPlanModelQuery
	withRoutes  *PricingPlanRouteQuery
	withAPIKeys *APIKeyQuery
	modifiers   []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PricingPlanQuery builder.
func (_q *PricingPlanQuery) Where(ps ...predicate.PricingPlan) *PricingPlanQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PricingPlanQuery) Limit(limit int) *PricingPlanQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PricingPlanQuery) Offset(offset int) *PricingPlanQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PricingPlanQuery) Unique(unique bool) *PricingPlanQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PricingPlanQuery) Order(o ...pricingplan.OrderOption) *PricingPlanQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryModels chains the current query on the "models" edge.
func (_q *PricingPlanQuery) QueryModels() *PricingPlanModelQuery {
	query := (&PricingPlanModelClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pricingplan.Table, pricingplan.FieldID, selector),
			sqlgraph.To(pricingplanmodel.Table, pricingplanmodel.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, pricingplan.ModelsTable, pricingplan.ModelsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoutes chains the current query on the "routes" edge.
func (_q *PricingPlanQuery) QueryRoutes() *PricingPlanRouteQuery {
	query := (&PricingPlanRouteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pricingplan.Table, pricingplan.FieldID, selector),
			sqlgraph.To(pricingplanroute.Table, pricingplanroute.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, pricingplan.RoutesTable, pricingplan.RoutesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryAPIKeys chains the current query on the "api_keys" edge.
func (_q *PricingPlanQuery) QueryAPIKeys() *APIKeyQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(pricingplan.Table, pricingplan.FieldID, selector),
			sqlgraph.To(apikey.Table, apikey.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, pricingplan.APIKeysTable, pricingplan.APIKeysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PricingPlan entity from the query.
// Returns a *NotFoundError when no PricingPlan was found.
func (_q *PricingPlanQuery) First(ctx context.Context) (*PricingPlan, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{pricingplan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PricingPlanQuery) FirstX(ctx context.Context) *PricingPlan {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PricingPlan ID from the query.
// Returns a *NotFoundError when no PricingPlan ID was found.
func (_q *PricingPlanQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{pricingplan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PricingPlanQuery) FirstIDX(ctx context.Context) int64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PricingPlan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PricingPlan entity is found.
// Returns a *NotFoundError when no PricingPlan entities are found.
func (_q *PricingPlanQuery) Only(ctx context.Context) (*PricingPlan, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{pricingplan.Label}
	default:
		return nil, &NotSingularError{pricingplan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PricingPlanQuery) OnlyX(ctx context.Context) *PricingPlan {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PricingPlan ID in the query.
// Returns a *NotSingularError when more than one PricingPlan ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PricingPlanQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{pricingplan.Label}
	default:
		err = &NotSingularError{pricingplan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PricingPlanQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PricingPlans.
func (_q *PricingPlanQuery) All(ctx context.Context) ([]*PricingPlan, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PricingPlan, *PricingPlanQuery]()
	return withInterceptors[[]*PricingPlan](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PricingPlanQuery) AllX(ctx context.Context) []*PricingPlan {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PricingPlan IDs.
func (_q *PricingPlanQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(pricingplan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PricingPlanQuery) IDsX(ctx context.Context) []int64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PricingPlanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PricingPlanQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PricingPlanQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PricingPlanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PricingPlanQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PricingPlanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PricingPlanQuery) Clone() *PricingPlanQuery {
	if _q == nil {
		return nil
	}
	return &PricingPlanQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]pricingplan.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.PricingPlan{}, _q.predicates...),
		withModels:  _q.withModels.Clone(),
		withRoutes:  _q.withRoutes.Clone(),
		withAPIKeys: _q.withAPIKeys.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithModels tells the query-builder to eager-load the nodes that are connected to
// the "models" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PricingPlanQuery) WithModels(opts ...func(*PricingPlanModelQuery)) *PricingPlanQuery {
	query := (&PricingPlanModelClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withModels = query
	return _q
}

// WithRoutes tells the query-builder to eager-load the nodes that are connected to
// the "routes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PricingPlanQuery) WithRoutes(opts ...func(*PricingPlanRouteQuery)) *PricingPlanQuery {
	query := (&PricingPlanRouteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withRoutes = query
	return _q
}

// WithAPIKeys tells the query-builder to eager-load the nodes that are connected to
// the "api_keys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PricingPlanQuery) WithAPIKeys(opts ...func(*APIKeyQuery)) *PricingPlanQuery {
	query := (&APIKeyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withAPIKeys = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PricingPlan.Query().
//		GroupBy(pricingplan.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PricingPlanQuery) GroupBy(field string, fields ...string) *PricingPlanGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PricingPlanGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = pricingplan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.PricingPlan.Query().
//		Select(pricingplan.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *PricingPlanQuery) Select(fields ...string) *PricingPlanSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PricingPlanSelect{PricingPlanQuery: _q}
	sbuild.label = pricingplan.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PricingPlanSelect configured with the given aggregations.
func (_q *PricingPlanQuery) Aggregate(fns ...AggregateFunc) *PricingPlanSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PricingPlanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !pricingplan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PricingPlanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PricingPlan, error) {
	var (
		nodes       = []*PricingPlan{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withModels != nil,
			_q.withRoutes != nil,
			_q.withAPIKeys != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PricingPlan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PricingPlan{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withModels; query != nil {
		if err := _q.loadModels(ctx, query, nodes,
			func(n *PricingPlan) { n.Edges.Models = []*PricingPlanModel{} },
			func(n *PricingPlan, e *PricingPlanModel) { n.Edges.Models = append(n.Edges.Models, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withRoutes; query != nil {
		if err := _q.loadRoutes(ctx, query, nodes,
			func(n *PricingPlan) { n.Edges.Routes = []*PricingPlanRoute{} },
			func(n *PricingPlan, e *PricingPlanRoute) { n.Edges.Routes = append(n.Edges.Routes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withAPIKeys; query != nil {
		if err := _q.loadAPIKeys(ctx, query, nodes,
			func(n *PricingPlan) { n.Edges.APIKeys = []*APIKey{} },
			func(n *PricingPlan, e *APIKey) { n.Edges.APIKeys = append(n.Edges.APIKeys, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PricingPlanQuery) loadModels(ctx context.Context, query *PricingPlanModelQuery, nodes []*PricingPlan, init func(*PricingPlan), assign func(*PricingPlan, *PricingPlanModel)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*PricingPlan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(pricingplanmodel.FieldPlanID)
	}
	query.Where(predicate.PricingPlanModel(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(pricingplan.ModelsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PlanID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PricingPlanQuery) loadRoutes(ctx context.Context, query *PricingPlanRouteQuery, nodes []*PricingPlan, init func(*PricingPlan), assign func(*PricingPlan, *PricingPlanRoute)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*PricingPlan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(pricingplanroute.FieldPlanID)
	}
	query.Where(predicate.PricingPlanRoute(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(pricingplan.RoutesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PlanID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "plan_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PricingPlanQuery) loadAPIKeys(ctx context.Context, query *APIKeyQuery, nodes []*PricingPlan, init func(*PricingPlan), assign func(*PricingPlan, *APIKey)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*PricingPlan)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(apikey.FieldPricingPlanID)
	}
	query.Where(predicate.APIKey(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(pricingplan.APIKeysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.PricingPlanID
		if fk == nil {
			return fmt.Errorf(`foreign-key "pricing_plan_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "pricing_plan_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *PricingPlanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	if len(_q.modifiers) > 0 {
		_spec.Modifiers = _q.modifiers
	}
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PricingPlanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(pricingplan.Table, pricingplan.Columns, sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingplan.FieldID)
		for i := range fields {
			if fields[i] != pricingplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PricingPlanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(pricingplan.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = pricingplan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range _q.modifiers {
		m(selector)
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ForUpdate locks the selected rows against concurrent updates, and prevent them from being
// updated, deleted or "selected ... for update" by other sessions, until the transaction is
// either committed or rolled-back.
func (_q *PricingPlanQuery) ForUpdate(opts ...sql.LockOption) *PricingPlanQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForUpdate(opts...)
	})
	return _q
}

// ForShare behaves similarly to ForUpdate, except that it acquires a shared mode lock
// on any rows that are read. Other sessions can read the rows, but cannot modify them
// until your transaction commits.
func (_q *PricingPlanQuery) ForShare(opts ...sql.LockOption) *PricingPlanQuery {
	if _q.driver.Dialect() == dialect.Postgres {
		_q.Unique(false)
	}
	_q.modifiers = append(_q.modifiers, func(s *sql.Selector) {
		s.ForShare(opts...)
	})
	return _q
}

// PricingPlanGroupBy is the group-by builder for PricingPlan entities.
type PricingPlanGroupBy struct {
	selector
	build *PricingPlanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PricingPlanGroupBy) Aggregate(fns ...AggregateFunc) *PricingPlanGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PricingPlanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PricingPlanQuery, *PricingPlanGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PricingPlanGroupBy) sqlScan(ctx context.Context, root *PricingPlanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PricingPlanSelect is the builder for selecting fields of PricingPlan entities.
type PricingPlanSelect struct {
	*PricingPlanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PricingPlanSelect) Aggregate(fns ...AggregateFunc) *PricingPlanSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PricingPlanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PricingPlanQuery, *PricingPlanSelect](ctx, _s.PricingPlanQuery, _s, _s.inters, v)
}

func (_s *PricingPlanSelect) sqlScan(ctx context.Context, root *PricingPlanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
