// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanmodel"
	"github.com/Wei-Shaw/sub2api/internal/domain"
)

// PricingPlanModelUpdate is the builder for updating PricingPlanModel entities.
type PricingPlanModelUpdate struct {
	config
	hooks    []Hook
	mutation *PricingPlanModelMutation
}

// Where appends a list predicates to the PricingPlanModelUpdate builder.
func (_u *PricingPlanModelUpdate) Where(ps ...predicate.PricingPlanModel) *PricingPlanModelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingPlanModelUpdate) SetUpdatedAt(v time.Time) *PricingPlanModelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PricingPlanModelUpdate) SetDeletedAt(v time.Time) *PricingPlanModelUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillableDeletedAt(v *time.Time) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PricingPlanModelUpdate) ClearDeletedAt() *PricingPlanModelUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PricingPlanModelUpdate) SetPlanID(v int64) *PricingPlanModelUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillablePlanID(v *int64) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *PricingPlanModelUpdate) SetPublicModel(v string) *PricingPlanModelUpdate {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillablePublicModel(v *string) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *PricingPlanModelUpdate) SetProtocol(v string) *PricingPlanModelUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillableProtocol(v *string) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *PricingPlanModelUpdate) SetUpstreamModel(v string) *PricingPlanModelUpdate {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillableUpstreamModel(v *string) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetDirect sets the "direct" field.
func (_u *PricingPlanModelUpdate) SetDirect(v bool) *PricingPlanModelUpdate {
	_u.mutation.SetDirect(v)
	return _u
}

// SetNillableDirect sets the "direct" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillableDirect(v *bool) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetDirect(*v)
	}
	return _u
}

// SetAllowCompatibilityFallback sets the "allow_compatibility_fallback" field.
func (_u *PricingPlanModelUpdate) SetAllowCompatibilityFallback(v bool) *PricingPlanModelUpdate {
	_u.mutation.SetAllowCompatibilityFallback(v)
	return _u
}

// SetNillableAllowCompatibilityFallback sets the "allow_compatibility_fallback" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillableAllowCompatibilityFallback(v *bool) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetAllowCompatibilityFallback(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PricingPlanModelUpdate) SetPriority(v int) *PricingPlanModelUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillablePriority(v *int) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PricingPlanModelUpdate) AddPriority(v int) *PricingPlanModelUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PricingPlanModelUpdate) SetEnabled(v bool) *PricingPlanModelUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillableEnabled(v *bool) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PricingPlanModelUpdate) SetNotes(v string) *PricingPlanModelUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PricingPlanModelUpdate) SetNillableNotes(v *string) *PricingPlanModelUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PricingPlanModelUpdate) ClearNotes() *PricingPlanModelUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *PricingPlanModelUpdate) SetPricing(v *domain.PlanModelPricing) *PricingPlanModelUpdate {
	_u.mutation.SetPricing(v)
	return _u
}

// ClearPricing clears the value of the "pricing" field.
func (_u *PricingPlanModelUpdate) ClearPricing() *PricingPlanModelUpdate {
	_u.mutation.ClearPricing()
	return _u
}

// SetPlan sets the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanModelUpdate) SetPlan(v *PricingPlan) *PricingPlanModelUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PricingPlanModelMutation object of the builder.
func (_u *PricingPlanModelUpdate) Mutation() *PricingPlanModelMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanModelUpdate) ClearPlan() *PricingPlanModelUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PricingPlanModelUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPlanModelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PricingPlanModelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPlanModelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingPlanModelUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if pricingplanmodel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanmodel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPlanModelUpdate) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := pricingplanmodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := pricingplanmodel.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := pricingplanmodel.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.upstream_model": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PricingPlanModel.plan"`)
	}
	return nil
}

func (_u *PricingPlanModelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingplanmodel.Table, pricingplanmodel.Columns, sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplanmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplanmodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(pricingplanmodel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(pricingplanmodel.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(pricingplanmodel.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(pricingplanmodel.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direct(); ok {
		_spec.SetField(pricingplanmodel.FieldDirect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowCompatibilityFallback(); ok {
		_spec.SetField(pricingplanmodel.FieldAllowCompatibilityFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pricingplanmodel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(pricingplanmodel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pricingplanmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(pricingplanmodel.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(pricingplanmodel.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(pricingplanmodel.FieldPricing, field.TypeJSON, value)
	}
	if _u.mutation.PricingCleared() {
		_spec.ClearField(pricingplanmodel.FieldPricing, field.TypeJSON)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanmodel.PlanTable,
			Columns: []string{pricingplanmodel.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanmodel.PlanTable,
			Columns: []string{pricingplanmodel.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingplanmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PricingPlanModelUpdateOne is the builder for updating a single PricingPlanModel entity.
type PricingPlanModelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingPlanModelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingPlanModelUpdateOne) SetUpdatedAt(v time.Time) *PricingPlanModelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PricingPlanModelUpdateOne) SetDeletedAt(v time.Time) *PricingPlanModelUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillableDeletedAt(v *time.Time) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PricingPlanModelUpdateOne) ClearDeletedAt() *PricingPlanModelUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *PricingPlanModelUpdateOne) SetPlanID(v int64) *PricingPlanModelUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillablePlanID(v *int64) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// SetPublicModel sets the "public_model" field.
func (_u *PricingPlanModelUpdateOne) SetPublicModel(v string) *PricingPlanModelUpdateOne {
	_u.mutation.SetPublicModel(v)
	return _u
}

// SetNillablePublicModel sets the "public_model" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillablePublicModel(v *string) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetPublicModel(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *PricingPlanModelUpdateOne) SetProtocol(v string) *PricingPlanModelUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillableProtocol(v *string) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetUpstreamModel sets the "upstream_model" field.
func (_u *PricingPlanModelUpdateOne) SetUpstreamModel(v string) *PricingPlanModelUpdateOne {
	_u.mutation.SetUpstreamModel(v)
	return _u
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillableUpstreamModel(v *string) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetUpstreamModel(*v)
	}
	return _u
}

// SetDirect sets the "direct" field.
func (_u *PricingPlanModelUpdateOne) SetDirect(v bool) *PricingPlanModelUpdateOne {
	_u.mutation.SetDirect(v)
	return _u
}

// SetNillableDirect sets the "direct" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillableDirect(v *bool) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetDirect(*v)
	}
	return _u
}

// SetAllowCompatibilityFallback sets the "allow_compatibility_fallback" field.
func (_u *PricingPlanModelUpdateOne) SetAllowCompatibilityFallback(v bool) *PricingPlanModelUpdateOne {
	_u.mutation.SetAllowCompatibilityFallback(v)
	return _u
}

// SetNillableAllowCompatibilityFallback sets the "allow_compatibility_fallback" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillableAllowCompatibilityFallback(v *bool) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetAllowCompatibilityFallback(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *PricingPlanModelUpdateOne) SetPriority(v int) *PricingPlanModelUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillablePriority(v *int) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *PricingPlanModelUpdateOne) AddPriority(v int) *PricingPlanModelUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PricingPlanModelUpdateOne) SetEnabled(v bool) *PricingPlanModelUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillableEnabled(v *bool) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PricingPlanModelUpdateOne) SetNotes(v string) *PricingPlanModelUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PricingPlanModelUpdateOne) SetNillableNotes(v *string) *PricingPlanModelUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PricingPlanModelUpdateOne) ClearNotes() *PricingPlanModelUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetPricing sets the "pricing" field.
func (_u *PricingPlanModelUpdateOne) SetPricing(v *domain.PlanModelPricing) *PricingPlanModelUpdateOne {
	_u.mutation.SetPricing(v)
	return _u
}

// ClearPricing clears the value of the "pricing" field.
func (_u *PricingPlanModelUpdateOne) ClearPricing() *PricingPlanModelUpdateOne {
	_u.mutation.ClearPricing()
	return _u
}

// SetPlan sets the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanModelUpdateOne) SetPlan(v *PricingPlan) *PricingPlanModelUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the PricingPlanModelMutation object of the builder.
func (_u *PricingPlanModelUpdateOne) Mutation() *PricingPlanModelMutation {
	return _u.mutation
}

// ClearPlan clears the "plan" edge to the PricingPlan entity.
func (_u *PricingPlanModelUpdateOne) ClearPlan() *PricingPlanModelUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the PricingPlanModelUpdate builder.
func (_u *PricingPlanModelUpdateOne) Where(ps ...predicate.PricingPlanModel) *PricingPlanModelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PricingPlanModelUpdateOne) Select(field string, fields ...string) *PricingPlanModelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PricingPlanModel entity.
func (_u *PricingPlanModelUpdateOne) Save(ctx context.Context) (*PricingPlanModel, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPlanModelUpdateOne) SaveX(ctx context.Context) *PricingPlanModel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PricingPlanModelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPlanModelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingPlanModelUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if pricingplanmodel.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplanmodel.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplanmodel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPlanModelUpdateOne) check() error {
	if v, ok := _u.mutation.PublicModel(); ok {
		if err := pricingplanmodel.PublicModelValidator(v); err != nil {
			return &ValidationError{Name: "public_model", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.public_model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := pricingplanmodel.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpstreamModel(); ok {
		if err := pricingplanmodel.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PricingPlanModel.upstream_model": %w`, err)}
		}
	}
	if _u.mutation.PlanCleared() && len(_u.mutation.PlanIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PricingPlanModel.plan"`)
	}
	return nil
}

func (_u *PricingPlanModelUpdateOne) sqlSave(ctx context.Context) (_node *PricingPlanModel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingplanmodel.Table, pricingplanmodel.Columns, sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PricingPlanModel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingplanmodel.FieldID)
		for _, f := range fields {
			if !pricingplanmodel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricingplanmodel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplanmodel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplanmodel.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(pricingplanmodel.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.PublicModel(); ok {
		_spec.SetField(pricingplanmodel.FieldPublicModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(pricingplanmodel.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpstreamModel(); ok {
		_spec.SetField(pricingplanmodel.FieldUpstreamModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.Direct(); ok {
		_spec.SetField(pricingplanmodel.FieldDirect, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowCompatibilityFallback(); ok {
		_spec.SetField(pricingplanmodel.FieldAllowCompatibilityFallback, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(pricingplanmodel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(pricingplanmodel.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(pricingplanmodel.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(pricingplanmodel.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(pricingplanmodel.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.Pricing(); ok {
		_spec.SetField(pricingplanmodel.FieldPricing, field.TypeJSON, value)
	}
	if _u.mutation.PricingCleared() {
		_spec.ClearField(pricingplanmodel.FieldPricing, field.TypeJSON)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanmodel.PlanTable,
			Columns: []string{pricingplanmodel.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pricingplanmodel.PlanTable,
			Columns: []string{pricingplanmodel.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PricingPlanModel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingplanmodel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
