// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/pricingplan"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanmodel"
	"github.com/Wei-Shaw/sub2api/ent/pricingplanroute"
)

// PricingPlanUpdate is the builder for updating PricingPlan entities.
type PricingPlanUpdate struct {
	config
	hooks    []Hook
	mutation *PricingPlanMutation
}

// Where appends a list predicates to the PricingPlanUpdate builder.
func (_u *PricingPlanUpdate) Where(ps ...predicate.PricingPlan) *PricingPlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingPlanUpdate) SetUpdatedAt(v time.Time) *PricingPlanUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PricingPlanUpdate) SetDeletedAt(v time.Time) *PricingPlanUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PricingPlanUpdate) SetNillableDeletedAt(v *time.Time) *PricingPlanUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PricingPlanUpdate) ClearDeletedAt() *PricingPlanUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PricingPlanUpdate) SetName(v string) *PricingPlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PricingPlanUpdate) SetNillableName(v *string) *PricingPlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PricingPlanUpdate) SetTitle(v string) *PricingPlanUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PricingPlanUpdate) SetNillableTitle(v *string) *PricingPlanUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PricingPlanUpdate) SetDescription(v string) *PricingPlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PricingPlanUpdate) SetNillableDescription(v *string) *PricingPlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PricingPlanUpdate) ClearDescription() *PricingPlanUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PricingPlanUpdate) SetStatus(v string) *PricingPlanUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PricingPlanUpdate) SetNillableStatus(v *string) *PricingPlanUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PricingPlanUpdate) SetIsPublic(v bool) *PricingPlanUpdate {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PricingPlanUpdate) SetNillableIsPublic(v *bool) *PricingPlanUpdate {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PricingPlanUpdate) SetSortOrder(v int) *PricingPlanUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PricingPlanUpdate) SetNillableSortOrder(v *int) *PricingPlanUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PricingPlanUpdate) AddSortOrder(v int) *PricingPlanUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddModelIDs adds the "models" edge to the PricingPlanModel entity by IDs.
func (_u *PricingPlanUpdate) AddModelIDs(ids ...int64) *PricingPlanUpdate {
	_u.mutation.AddModelIDs(ids...)
	return _u
}

// AddModels adds the "models" edges to the PricingPlanModel entity.
func (_u *PricingPlanUpdate) AddModels(v ...*PricingPlanModel) *PricingPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelIDs(ids...)
}

// AddRouteIDs adds the "routes" edge to the PricingPlanRoute entity by IDs.
func (_u *PricingPlanUpdate) AddRouteIDs(ids ...int64) *PricingPlanUpdate {
	_u.mutation.AddRouteIDs(ids...)
	return _u
}

// AddRoutes adds the "routes" edges to the PricingPlanRoute entity.
func (_u *PricingPlanUpdate) AddRoutes(v ...*PricingPlanRoute) *PricingPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRouteIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *PricingPlanUpdate) AddAPIKeyIDs(ids ...int64) *PricingPlanUpdate {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *PricingPlanUpdate) AddAPIKeys(v ...*APIKey) *PricingPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// Mutation returns the PricingPlanMutation object of the builder.
func (_u *PricingPlanUpdate) Mutation() *PricingPlanMutation {
	return _u.mutation
}

// ClearModels clears all "models" edges to the PricingPlanModel entity.
func (_u *PricingPlanUpdate) ClearModels() *PricingPlanUpdate {
	_u.mutation.ClearModels()
	return _u
}

// RemoveModelIDs removes the "models" edge to PricingPlanModel entities by IDs.
func (_u *PricingPlanUpdate) RemoveModelIDs(ids ...int64) *PricingPlanUpdate {
	_u.mutation.RemoveModelIDs(ids...)
	return _u
}

// RemoveModels removes "models" edges to PricingPlanModel entities.
func (_u *PricingPlanUpdate) RemoveModels(v ...*PricingPlanModel) *PricingPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelIDs(ids...)
}

// ClearRoutes clears all "routes" edges to the PricingPlanRoute entity.
func (_u *PricingPlanUpdate) ClearRoutes() *PricingPlanUpdate {
	_u.mutation.ClearRoutes()
	return _u
}

// RemoveRouteIDs removes the "routes" edge to PricingPlanRoute entities by IDs.
func (_u *PricingPlanUpdate) RemoveRouteIDs(ids ...int64) *PricingPlanUpdate {
	_u.mutation.RemoveRouteIDs(ids...)
	return _u
}

// RemoveRoutes removes "routes" edges to PricingPlanRoute entities.
func (_u *PricingPlanUpdate) RemoveRoutes(v ...*PricingPlanRoute) *PricingPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRouteIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *PricingPlanUpdate) ClearAPIKeys() *PricingPlanUpdate {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *PricingPlanUpdate) RemoveAPIKeyIDs(ids ...int64) *PricingPlanUpdate {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *PricingPlanUpdate) RemoveAPIKeys(v ...*APIKey) *PricingPlanUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PricingPlanUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PricingPlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingPlanUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if pricingplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPlanUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := pricingplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := pricingplan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pricingplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingPlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingplan.Table, pricingplan.Columns, sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(pricingplan.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pricingplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(pricingplan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(pricingplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(pricingplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pricingplan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(pricingplan.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(pricingplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(pricingplan.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.ModelsTable,
			Columns: []string{pricingplan.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelsIDs(); len(nodes) > 0 && !_u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.ModelsTable,
			Columns: []string{pricingplan.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.ModelsTable,
			Columns: []string{pricingplan.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.RoutesTable,
			Columns: []string{pricingplan.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !_u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.RoutesTable,
			Columns: []string{pricingplan.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.RoutesTable,
			Columns: []string{pricingplan.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricingplan.APIKeysTable,
			Columns: []string{pricingplan.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricingplan.APIKeysTable,
			Columns: []string{pricingplan.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricingplan.APIKeysTable,
			Columns: []string{pricingplan.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PricingPlanUpdateOne is the builder for updating a single PricingPlan entity.
type PricingPlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PricingPlanMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PricingPlanUpdateOne) SetUpdatedAt(v time.Time) *PricingPlanUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PricingPlanUpdateOne) SetDeletedAt(v time.Time) *PricingPlanUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PricingPlanUpdateOne) SetNillableDeletedAt(v *time.Time) *PricingPlanUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PricingPlanUpdateOne) ClearDeletedAt() *PricingPlanUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *PricingPlanUpdateOne) SetName(v string) *PricingPlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PricingPlanUpdateOne) SetNillableName(v *string) *PricingPlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PricingPlanUpdateOne) SetTitle(v string) *PricingPlanUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PricingPlanUpdateOne) SetNillableTitle(v *string) *PricingPlanUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PricingPlanUpdateOne) SetDescription(v string) *PricingPlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PricingPlanUpdateOne) SetNillableDescription(v *string) *PricingPlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PricingPlanUpdateOne) ClearDescription() *PricingPlanUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetStatus sets the "status" field.
func (_u *PricingPlanUpdateOne) SetStatus(v string) *PricingPlanUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PricingPlanUpdateOne) SetNillableStatus(v *string) *PricingPlanUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsPublic sets the "is_public" field.
func (_u *PricingPlanUpdateOne) SetIsPublic(v bool) *PricingPlanUpdateOne {
	_u.mutation.SetIsPublic(v)
	return _u
}

// SetNillableIsPublic sets the "is_public" field if the given value is not nil.
func (_u *PricingPlanUpdateOne) SetNillableIsPublic(v *bool) *PricingPlanUpdateOne {
	if v != nil {
		_u.SetIsPublic(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *PricingPlanUpdateOne) SetSortOrder(v int) *PricingPlanUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *PricingPlanUpdateOne) SetNillableSortOrder(v *int) *PricingPlanUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *PricingPlanUpdateOne) AddSortOrder(v int) *PricingPlanUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// AddModelIDs adds the "models" edge to the PricingPlanModel entity by IDs.
func (_u *PricingPlanUpdateOne) AddModelIDs(ids ...int64) *PricingPlanUpdateOne {
	_u.mutation.AddModelIDs(ids...)
	return _u
}

// AddModels adds the "models" edges to the PricingPlanModel entity.
func (_u *PricingPlanUpdateOne) AddModels(v ...*PricingPlanModel) *PricingPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddModelIDs(ids...)
}

// AddRouteIDs adds the "routes" edge to the PricingPlanRoute entity by IDs.
func (_u *PricingPlanUpdateOne) AddRouteIDs(ids ...int64) *PricingPlanUpdateOne {
	_u.mutation.AddRouteIDs(ids...)
	return _u
}

// AddRoutes adds the "routes" edges to the PricingPlanRoute entity.
func (_u *PricingPlanUpdateOne) AddRoutes(v ...*PricingPlanRoute) *PricingPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRouteIDs(ids...)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (_u *PricingPlanUpdateOne) AddAPIKeyIDs(ids ...int64) *PricingPlanUpdateOne {
	_u.mutation.AddAPIKeyIDs(ids...)
	return _u
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (_u *PricingPlanUpdateOne) AddAPIKeys(v ...*APIKey) *PricingPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPIKeyIDs(ids...)
}

// Mutation returns the PricingPlanMutation object of the builder.
func (_u *PricingPlanUpdateOne) Mutation() *PricingPlanMutation {
	return _u.mutation
}

// ClearModels clears all "models" edges to the PricingPlanModel entity.
func (_u *PricingPlanUpdateOne) ClearModels() *PricingPlanUpdateOne {
	_u.mutation.ClearModels()
	return _u
}

// RemoveModelIDs removes the "models" edge to PricingPlanModel entities by IDs.
func (_u *PricingPlanUpdateOne) RemoveModelIDs(ids ...int64) *PricingPlanUpdateOne {
	_u.mutation.RemoveModelIDs(ids...)
	return _u
}

// RemoveModels removes "models" edges to PricingPlanModel entities.
func (_u *PricingPlanUpdateOne) RemoveModels(v ...*PricingPlanModel) *PricingPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveModelIDs(ids...)
}

// ClearRoutes clears all "routes" edges to the PricingPlanRoute entity.
func (_u *PricingPlanUpdateOne) ClearRoutes() *PricingPlanUpdateOne {
	_u.mutation.ClearRoutes()
	return _u
}

// RemoveRouteIDs removes the "routes" edge to PricingPlanRoute entities by IDs.
func (_u *PricingPlanUpdateOne) RemoveRouteIDs(ids ...int64) *PricingPlanUpdateOne {
	_u.mutation.RemoveRouteIDs(ids...)
	return _u
}

// RemoveRoutes removes "routes" edges to PricingPlanRoute entities.
func (_u *PricingPlanUpdateOne) RemoveRoutes(v ...*PricingPlanRoute) *PricingPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRouteIDs(ids...)
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (_u *PricingPlanUpdateOne) ClearAPIKeys() *PricingPlanUpdateOne {
	_u.mutation.ClearAPIKeys()
	return _u
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (_u *PricingPlanUpdateOne) RemoveAPIKeyIDs(ids ...int64) *PricingPlanUpdateOne {
	_u.mutation.RemoveAPIKeyIDs(ids...)
	return _u
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (_u *PricingPlanUpdateOne) RemoveAPIKeys(v ...*APIKey) *PricingPlanUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPIKeyIDs(ids...)
}

// Where appends a list predicates to the PricingPlanUpdate builder.
func (_u *PricingPlanUpdateOne) Where(ps ...predicate.PricingPlan) *PricingPlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PricingPlanUpdateOne) Select(field string, fields ...string) *PricingPlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PricingPlan entity.
func (_u *PricingPlanUpdateOne) Save(ctx context.Context) (*PricingPlan, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PricingPlanUpdateOne) SaveX(ctx context.Context) *PricingPlan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PricingPlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PricingPlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PricingPlanUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if pricingplan.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized pricingplan.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := pricingplan.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PricingPlanUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := pricingplan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Title(); ok {
		if err := pricingplan.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := pricingplan.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PricingPlan.status": %w`, err)}
		}
	}
	return nil
}

func (_u *PricingPlanUpdateOne) sqlSave(ctx context.Context) (_node *PricingPlan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pricingplan.Table, pricingplan.Columns, sqlgraph.NewFieldSpec(pricingplan.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PricingPlan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pricingplan.FieldID)
		for _, f := range fields {
			if !pricingplan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pricingplan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(pricingplan.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(pricingplan.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(pricingplan.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(pricingplan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(pricingplan.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(pricingplan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(pricingplan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(pricingplan.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsPublic(); ok {
		_spec.SetField(pricingplan.FieldIsPublic, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(pricingplan.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(pricingplan.FieldSortOrder, field.TypeInt, value)
	}
	if _u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.ModelsTable,
			Columns: []string{pricingplan.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedModelsIDs(); len(nodes) > 0 && !_u.mutation.ModelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.ModelsTable,
			Columns: []string{pricingplan.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ModelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.ModelsTable,
			Columns: []string{pricingplan.ModelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanmodel.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.RoutesTable,
			Columns: []string{pricingplan.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRoutesIDs(); len(nodes) > 0 && !_u.mutation.RoutesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.RoutesTable,
			Columns: []string{pricingplan.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RoutesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   pricingplan.RoutesTable,
			Columns: []string{pricingplan.RoutesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pricingplanroute.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricingplan.APIKeysTable,
			Columns: []string{pricingplan.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !_u.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricingplan.APIKeysTable,
			Columns: []string{pricingplan.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   pricingplan.APIKeysTable,
			Columns: []string{pricingplan.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PricingPlan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pricingplan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
