import { ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useAppStore } from '@/stores/app'
import { adminAPI } from '@/api/admin'
import type { ZhipuLoginCredential, ZhipuLoginUrlRequest } from '@/api/admin/zhipu'
import { extractI18nErrorMessage } from '@/utils/apiError'

/**
 * Zhipu (bigmodel) login state machine for the admin UI.
 *
 * idle → generating → awaiting_code → exchanging → ready | error
 *
 * Follows the Grok OAuth composable shape (`useGrokOAuth`), but exposes the flow as an
 * explicit state machine so the create/relogin modals can drive
 * `OAuthAuthorizationFlow.vue` (open link → paste authCode) without inventing UI state.
 */
export type ZhipuOAuthStatus =
  | 'idle'
  | 'generating'
  | 'awaiting_code'
  | 'exchanging'
  | 'ready'
  | 'error'

export interface ZhipuGenerateLoginUrlOptions {
  proxyId?: number | null
  redirectUri?: string
}

export interface ZhipuExchangeAuthCodeParams {
  code: string
  sessionId?: string
  state?: string
}

export function useZhipuOAuth() {
  const appStore = useAppStore()
  const { t } = useI18n()

  const status = ref<ZhipuOAuthStatus>('idle')
  const loginUrl = ref('')
  const sessionId = ref('')
  const state = ref('')
  const credential = ref<ZhipuLoginCredential | null>(null)
  const errorMessage = ref('')

  // Backend messages are localized server-side (`Accept-Language`); this ticket introduces
  // no new frontend i18n keys. Adding `admin.accounts.oauth.zhipu.errors.*` later localizes
  // the `ZHIPU_OAUTH_*` codes without touching the composable.
  const resolveErrorMessage = (err: unknown): string =>
    extractI18nErrorMessage(
      err,
      t,
      'admin.accounts.oauth.zhipu.errors',
      t('common.unknownError')
    )

  const reset = () => {
    status.value = 'idle'
    loginUrl.value = ''
    sessionId.value = ''
    state.value = ''
    credential.value = null
    errorMessage.value = ''
  }

  const generateLoginUrl = async (
    options: ZhipuGenerateLoginUrlOptions = {}
  ): Promise<boolean> => {
    status.value = 'generating'
    loginUrl.value = ''
    sessionId.value = ''
    state.value = ''
    credential.value = null
    errorMessage.value = ''

    const payload: ZhipuLoginUrlRequest = {}
    if (options.proxyId) payload.proxy_id = options.proxyId
    if (options.redirectUri) payload.redirect_uri = options.redirectUri

    try {
      const response = await adminAPI.zhipu.generateLoginUrl(payload)
      loginUrl.value = response.login_url
      sessionId.value = response.session_id
      state.value = response.state
      status.value = 'awaiting_code'
      return true
    } catch (err) {
      errorMessage.value = resolveErrorMessage(err)
      status.value = 'error'
      appStore.showError(errorMessage.value)
      return false
    }
  }

  const exchangeAuthCode = async (
    params: ZhipuExchangeAuthCodeParams
  ): Promise<ZhipuLoginCredential | null> => {
    status.value = 'exchanging'
    errorMessage.value = ''

    try {
      const result = await adminAPI.zhipu.exchange({
        session_id: params.sessionId ?? sessionId.value,
        state: params.state ?? state.value,
        auth_code: params.code?.trim() ?? '',
      })
      credential.value = result
      status.value = 'ready'
      return result
    } catch (err) {
      credential.value = null
      errorMessage.value = resolveErrorMessage(err)
      status.value = 'error'
      appStore.showError(errorMessage.value)
      return null
    }
  }

  /**
   * Re-login a managed account (ticket 07) reusing the session generated by
   * `generateLoginUrl`: exchange → re-resolve api_key → merge credentials server-side.
   */
  const relogin = async (accountId: number, params: { code: string }): Promise<boolean> => {
    status.value = 'exchanging'
    errorMessage.value = ''

    try {
      await adminAPI.zhipu.relogin(accountId, {
        session_id: sessionId.value,
        state: state.value,
        auth_code: params.code?.trim() ?? '',
      })
      credential.value = null
      status.value = 'ready'
      return true
    } catch (err) {
      errorMessage.value = resolveErrorMessage(err)
      status.value = 'error'
      appStore.showError(errorMessage.value)
      return false
    }
  }

  return {
    status,
    loginUrl,
    sessionId,
    state,
    credential,
    errorMessage,
    reset,
    generateLoginUrl,
    exchangeAuthCode,
    relogin,
  }
}
